"""
================================================================================
ALGORITHM & ARCHITECTURE BLUEPRINT: GENERATED CODE CLASSIFIER (ALGO 08)
================================================================================

1. OVERVIEW & OBJECTIVE:
   Token signature detector scanning file headers to identify autogenerated
   source files (Protobuf, OpenAPI, GraphQL codegen, mocks) to skip them during
   architectural refactoring passes.

2. COMPLEXITY & INVARIANTS:
   - Time Complexity: O(min(Lines, 20)) header scanning.
   - Space Complexity: O(1).
   - Rules Enforced: R1 (Read Before Write).
   - Guardrails: G2 (Strict Deny-List on Machine-Generated Files).

3. EXECUTION FLOW:
   Reads first 20 lines and matches against known generator signatures
   (`@generated`, `Code generated by`, `DO NOT EDIT`, `AUTO-GENERATED`).
================================================================================
"""

import os

GENERATED_SIGNATURES = [
    "@generated",
    "code generated by",
    "do not edit",
    "auto-generated",
    "generated by protobuf",
    "this file is generated",
    "automatically generated",
]

class SearchEngineGeneratedCodeClassifierAlgo:
    """
    ---
    contract:
      algo_id: ALGO-SRCH-08
      name: SearchEngineGeneratedCodeClassifierAlgo
      version: 1.0.0
      category: search
      capability_tags:
      - classifier.generated_code
      - filter.minified
      - filter.lockfile
      inputs:
        type: object
        required:
        - file_path
        - content_header
        properties:
          file_path:
            type: string
          content_header:
            type: string
      outputs:
        type: object
        required:
        - is_generated
        properties:
          is_generated:
            type: boolean
          marker:
            type: string
            nullable: true
      parameters:
        type: object
        properties: {}
      purity: PURE
      determinism: DETERMINISTIC
      idempotency: IDEMPOTENT
      complexity:
        time: O(HeaderLength)
        space: O(1)
      preconditions:
      - len(input.file_path) > 0
      postconditions:
      - isinstance(output.is_generated, bool)
      compatible_adapters: []
    ---
    """
    @staticmethod
    def is_generated(file_path: str, max_lines_to_check: int = 20) -> bool:
        if not os.path.isfile(file_path):
            return False
        try:
            with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
                for idx, line in enumerate(f):
                    if idx >= max_lines_to_check:
                        break
                    line_lower = line.lower()
                    if any(sig in line_lower for sig in GENERATED_SIGNATURES):
                        return True
        except Exception:
            return False
        return False
