"""
================================================================================
ALGORITHM & ARCHITECTURE BLUEPRINT: GENERATED CODE CLASSIFIER (ALGO-CLS-02)
================================================================================

1. OVERVIEW & OBJECTIVE:
   Token signature detector scanning file headers to identify autogenerated
   source files (Protobuf, OpenAPI, GraphQL codegen, mocks, build artifacts)
   to classify and selectively skip them during architectural refactoring passes.

2. ARCHITECTURAL ROLE:
   Classification & Filtering role (Layer 1). Prevents LLM code mutations
   or AST index pollution on machine-generated source files.

3. COMPLEXITY & INVARIANTS:
   - Time Complexity: O(min(Lines, MaxLinesToCheck) * LineLength).
   - Space Complexity: O(1).
   - Rules Enforced: R1 (Read Before Write).
   - Guardrails: G2 (Strict Deny-List on Machine-Generated Files).
   - Zero-Inline-Comment Doctrine: Code body is 100% comment-free.

4. EXECUTION FLOW:
   a. Verify file existence.
   b. Read up to max_lines_to_check lines (default 20) with UTF-8 ignore fallback.
   c. Match each line against known generator signatures.
   d. Return True if generator signature matched, else False.
================================================================================
"""

import os
from typing import List

GENERATED_SIGNATURES: List[str] = [
    "@generated",
    "code generated by",
    "do not edit",
    "auto-generated",
    "generated by protobuf",
    "this file is generated",
    "automatically generated",
]


class ClassifierAlgoGeneratedCode:
    """
    --- contract:
      id: ALGO-CLS-02
      name: ClassifierAlgoGeneratedCode
      version: 1.0.0
      category: classifier
      complexity:
        time: O(min(Lines, MaxLinesToCheck) * LineLength)
        space: O(1)
      pure_function: false
      zero_inline_comments: true
      capability_tags:
        - classifier.generated_code
        - filter.minified
        - filter.codegen
      input_schema:
        file_path: string
        max_lines_to_check: int
      output_schema:
        is_generated: bool
    ---
    """

    @staticmethod
    def is_generated(file_path: str, max_lines_to_check: int = 20) -> bool:
        if not os.path.isfile(file_path):
            return False

        try:
            with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
                for idx, line in enumerate(f):
                    if idx >= max_lines_to_check:
                        break
                    line_lower = line.lower()
                    if any(sig in line_lower for sig in GENERATED_SIGNATURES):
                        return True
        except (OSError, PermissionError):
            return False

        return False


SearchEngineGeneratedCodeClassifierAlgo = ClassifierAlgoGeneratedCode
