"""
================================================================================
ALGORITHM & ARCHITECTURE BLUEPRINT: CODE ENGINE ALGORITHM CATALOG SEEDS
================================================================================

1. OVERVIEW & OBJECTIVE:
   Provides declarative Layer 1 (G1-G6) contract seed definitions for all 24
   foundational Search, Observability, and Update algorithms and standard G4 Adapters.

2. TAXONOMY:
   - Search: ALGO-SRCH-01 through ALGO-SRCH-15
   - Observability: ALGO-OBS-16 through ALGO-OBS-21
   - Update: ALGO-UPD-22 through ALGO-UPD-24
================================================================================
"""

from typing import List
from src.domain.models.algorithm_contract import (
    AlgorithmContract,
    AlgorithmCategory,
    Purity,
    Determinism,
    Idempotency,
    Reversibility,
    SideEffectScope,
    ConcurrencyModel,
    HardwareTarget,
    ComplexityCost,
    TypeAdapterContract,
)

BUILTIN_ALGORITHM_CONTRACTS: List[AlgorithmContract] = [
    # -------------------------------------------------------------------------
    # SEARCH ALGORITHMS (01 - 15)
    # -------------------------------------------------------------------------
    AlgorithmContract(
        id="ALGO-SRCH-01",
        name="SearchEngineRecursiveWalkAlgo",
        version="1.0.0",
        category=AlgorithmCategory.SEARCH,
        capability_tags=["filesystem.traversal", "directory.walk.dfs", "filter.ignored_dirs"],
        input_schema={"type": "object", "required": ["root_dir"], "properties": {"root_dir": {"type": "string"}}},
        output_schema={"type": "array", "items": {"type": "string", "description": "Absolute file path"}},
        parameters_schema={
            "type": "object",
            "properties": {
                "max_depth": {"type": "integer", "default": 16, "minimum": 1},
                "allowed_extensions": {"type": "array", "items": {"type": "string"}},
                "ignored_names": {"type": "array", "items": {"type": "string"}},
            },
        },
        purity=Purity.IMPURE,
        determinism=Determinism.DETERMINISTIC,
        idempotency=Idempotency.IDEMPOTENT,
        reversibility=Reversibility.REVERSIBLE,
        side_effects=SideEffectScope.READ_ONLY,
        concurrency_model=ConcurrencyModel.THREAD_SAFE,
        hardware_target=HardwareTarget.CPU_SCALAR,
        complexity=ComplexityCost(time="O(N)", space="O(D)"),
        preconditions=["os.path.isdir(input.root_dir) == True"],
        postconditions=["is_sorted(output)", "all(os.path.isfile(p) for p in output)"],
        compatible_adapters=["ADAPTER-FILE-PATH-TO-CONTENT", "ADAPTER-FILE-PATH-TO-AST"],
    ),
    AlgorithmContract(
        id="ALGO-SRCH-02",
        name="SearchEngineWorkStealingWalkerAlgo",
        version="1.0.0",
        category=AlgorithmCategory.SEARCH,
        capability_tags=["filesystem.traversal", "directory.walk.parallel", "concurrency.work_stealing"],
        input_schema={"type": "object", "required": ["root_dir"], "properties": {"root_dir": {"type": "string"}}},
        output_schema={"type": "array", "items": {"type": "string"}},
        parameters_schema={
            "type": "object",
            "properties": {
                "num_workers": {"type": "integer", "minimum": 1},
                "allowed_extensions": {"type": "array", "items": {"type": "string"}},
            },
        },
        purity=Purity.IMPURE,
        determinism=Determinism.DETERMINISTIC,
        idempotency=Idempotency.IDEMPOTENT,
        reversibility=Reversibility.REVERSIBLE,
        side_effects=SideEffectScope.READ_ONLY,
        concurrency_model=ConcurrencyModel.PROCESS_ISOLATED,
        hardware_target=HardwareTarget.CPU_SCALAR,
        complexity=ComplexityCost(time="O(N/P)", space="O(N)"),
        preconditions=["os.path.isdir(input.root_dir) == True"],
        postconditions=["is_sorted(output)"],
        compatible_adapters=["ADAPTER-FILE-PATH-TO-CONTENT"],
    ),
    AlgorithmContract(
        id="ALGO-SRCH-03",
        name="SearchEngineGitAwareWalkerAlgo",
        version="1.0.0",
        category=AlgorithmCategory.SEARCH,
        capability_tags=["filesystem.traversal", "git.ignore.aware", "vcs.filter"],
        input_schema={"type": "object", "required": ["root_dir"], "properties": {"root_dir": {"type": "string"}}},
        output_schema={"type": "array", "items": {"type": "string"}},
        parameters_schema={"type": "object", "properties": {"respect_gitignore": {"type": "boolean", "default": True}}},
        purity=Purity.IMPURE,
        determinism=Determinism.DETERMINISTIC,
        idempotency=Idempotency.IDEMPOTENT,
        reversibility=Reversibility.REVERSIBLE,
        side_effects=SideEffectScope.READ_ONLY,
        concurrency_model=ConcurrencyModel.THREAD_SAFE,
        hardware_target=HardwareTarget.CPU_SCALAR,
        complexity=ComplexityCost(time="O(N)", space="O(N)"),
        preconditions=["os.path.isdir(input.root_dir) == True"],
        postconditions=["is_sorted(output)", "not_contains(output, '.git')"],
        compatible_adapters=["ADAPTER-FILE-PATH-TO-CONTENT"],
    ),
    AlgorithmContract(
        id="ALGO-SRCH-04",
        name="SearchEngineGlobMatcherAlgo",
        version="1.0.0",
        category=AlgorithmCategory.SEARCH,
        capability_tags=["filter.path", "glob.match", "fnmatch"],
        input_schema={
            "type": "object",
            "required": ["paths", "include_patterns"],
            "properties": {
                "paths": {"type": "array", "items": {"type": "string"}},
                "include_patterns": {"type": "array", "items": {"type": "string"}},
            },
        },
        output_schema={"type": "array", "items": {"type": "string"}},
        parameters_schema={"type": "object", "properties": {"exclude_patterns": {"type": "array", "items": {"type": "string"}}}},
        purity=Purity.PURE,
        determinism=Determinism.DETERMINISTIC,
        idempotency=Idempotency.IDEMPOTENT,
        reversibility=Reversibility.REVERSIBLE,
        side_effects=SideEffectScope.IN_MEMORY,
        concurrency_model=ConcurrencyModel.THREAD_SAFE,
        hardware_target=HardwareTarget.CPU_SCALAR,
        complexity=ComplexityCost(time="O(N * P)", space="O(N)"),
        preconditions=["len(input.include_patterns) > 0"],
        postconditions=["set(output).issubset(set(input.paths))"],
        compatible_adapters=["ADAPTER-FILE-PATH-TO-CONTENT"],
    ),
    AlgorithmContract(
        id="ALGO-SRCH-05",
        name="SearchEngineBinaryClassifierAlgo",
        version="1.0.0",
        category=AlgorithmCategory.SEARCH,
        capability_tags=["classifier.binary", "filter.text", "probe.null_byte"],
        input_schema={"type": "object", "required": ["file_path"], "properties": {"file_path": {"type": "string"}}},
        output_schema={"type": "object", "required": ["is_text"], "properties": {"is_text": {"type": "boolean"}}},
        parameters_schema={"type": "object", "properties": {"sample_size": {"type": "integer", "default": 1024}}},
        purity=Purity.IMPURE,
        determinism=Determinism.DETERMINISTIC,
        idempotency=Idempotency.IDEMPOTENT,
        reversibility=Reversibility.REVERSIBLE,
        side_effects=SideEffectScope.READ_ONLY,
        concurrency_model=ConcurrencyModel.THREAD_SAFE,
        hardware_target=HardwareTarget.CPU_SCALAR,
        complexity=ComplexityCost(time="O(min(FileSize, SampleSize))", space="O(1)"),
        preconditions=["os.path.isfile(input.file_path) == True"],
        postconditions=["isinstance(output.is_text, bool)"],
        compatible_adapters=[],
    ),
    AlgorithmContract(
        id="ALGO-SRCH-06",
        name="SearchEngineContentTypeProberAlgo",
        version="1.0.0",
        category=AlgorithmCategory.SEARCH,
        capability_tags=["classifier.mime", "probe.content_type", "magic_bytes"],
        input_schema={"type": "object", "required": ["file_path"], "properties": {"file_path": {"type": "string"}}},
        output_schema={
            "type": "object",
            "required": ["mime_type", "encoding"],
            "properties": {"mime_type": {"type": "string"}, "encoding": {"type": "string"}},
        },
        parameters_schema={"type": "object", "properties": {}},
        purity=Purity.IMPURE,
        determinism=Determinism.DETERMINISTIC,
        idempotency=Idempotency.IDEMPOTENT,
        reversibility=Reversibility.REVERSIBLE,
        side_effects=SideEffectScope.READ_ONLY,
        concurrency_model=ConcurrencyModel.THREAD_SAFE,
        hardware_target=HardwareTarget.CPU_SCALAR,
        complexity=ComplexityCost(time="O(1)", space="O(1)"),
        preconditions=["os.path.isfile(input.file_path) == True"],
        postconditions=["len(output.mime_type) > 0"],
        compatible_adapters=[],
    ),
    AlgorithmContract(
        id="ALGO-SRCH-07",
        name="SearchEngineSizeLineBouncerAlgo",
        version="1.0.0",
        category=AlgorithmCategory.SEARCH,
        capability_tags=["filter.size", "guardrail.resource", "bouncer.line_length"],
        input_schema={"type": "object", "required": ["file_path"], "properties": {"file_path": {"type": "string"}}},
        output_schema={
            "type": "object",
            "required": ["is_acceptable"],
            "properties": {"is_acceptable": {"type": "boolean"}, "rejection_reason": {"type": "string", "nullable": True}},
        },
        parameters_schema={
            "type": "object",
            "properties": {
                "max_bytes": {"type": "integer", "default": 5000000},
                "max_line_length": {"type": "integer", "default": 10000},
            },
        },
        purity=Purity.IMPURE,
        determinism=Determinism.DETERMINISTIC,
        idempotency=Idempotency.IDEMPOTENT,
        reversibility=Reversibility.REVERSIBLE,
        side_effects=SideEffectScope.READ_ONLY,
        concurrency_model=ConcurrencyModel.THREAD_SAFE,
        hardware_target=HardwareTarget.CPU_SCALAR,
        complexity=ComplexityCost(time="O(K)", space="O(1)"),
        preconditions=["os.path.isfile(input.file_path) == True"],
        postconditions=["isinstance(output.is_acceptable, bool)"],
        compatible_adapters=[],
    ),
    AlgorithmContract(
        id="ALGO-SRCH-08",
        name="SearchEngineGeneratedCodeClassifierAlgo",
        version="1.0.0",
        category=AlgorithmCategory.SEARCH,
        capability_tags=["classifier.generated_code", "filter.minified", "filter.lockfile"],
        input_schema={
            "type": "object",
            "required": ["file_path", "content_header"],
            "properties": {"file_path": {"type": "string"}, "content_header": {"type": "string"}},
        },
        output_schema={
            "type": "object",
            "required": ["is_generated"],
            "properties": {"is_generated": {"type": "boolean"}, "marker": {"type": "string", "nullable": True}},
        },
        parameters_schema={"type": "object", "properties": {}},
        purity=Purity.PURE,
        determinism=Determinism.DETERMINISTIC,
        idempotency=Idempotency.IDEMPOTENT,
        reversibility=Reversibility.REVERSIBLE,
        side_effects=SideEffectScope.IN_MEMORY,
        concurrency_model=ConcurrencyModel.THREAD_SAFE,
        hardware_target=HardwareTarget.CPU_SCALAR,
        complexity=ComplexityCost(time="O(HeaderLength)", space="O(1)"),
        preconditions=["len(input.file_path) > 0"],
        postconditions=["isinstance(output.is_generated, bool)"],
        compatible_adapters=[],
    ),
    AlgorithmContract(
        id="ALGO-SRCH-09",
        name="SearchEngineTrigramIndexAlgo",
        version="1.0.0",
        category=AlgorithmCategory.SEARCH,
        capability_tags=["index.trigram", "search.candidate_filter", "index.inverted"],
        input_schema={
            "type": "object",
            "required": ["documents"],
            "properties": {"documents": {"type": "object", "additionalProperties": {"type": "string"}}},
        },
        output_schema={"type": "object", "required": ["total_trigrams"], "properties": {"total_trigrams": {"type": "integer"}}},
        parameters_schema={"type": "object", "properties": {}},
        purity=Purity.PURE,
        determinism=Determinism.DETERMINISTIC,
        idempotency=Idempotency.IDEMPOTENT,
        reversibility=Reversibility.REVERSIBLE,
        side_effects=SideEffectScope.IN_MEMORY,
        concurrency_model=ConcurrencyModel.THREAD_SAFE,
        hardware_target=HardwareTarget.CPU_SCALAR,
        complexity=ComplexityCost(time="O(SumDocLength)", space="O(Trigrams)"),
        preconditions=["len(input.documents) > 0"],
        postconditions=["output.total_trigrams >= 0"],
        compatible_adapters=["ADAPTER-QUERY-TO-TRIGRAM-CANDIDATES"],
    ),
    AlgorithmContract(
        id="ALGO-SRCH-10",
        name="SearchEngineSimdMemchrAlgo",
        version="1.0.0",
        category=AlgorithmCategory.SEARCH,
        capability_tags=["search.raw_byte", "simd.memchr", "scan.fast_byte"],
        input_schema={
            "type": "object",
            "required": ["haystack", "needle"],
            "properties": {"haystack": {"type": "string"}, "needle": {"type": "string"}},
        },
        output_schema={"type": "array", "items": {"type": "integer", "description": "Byte offset"}},
        parameters_schema={"type": "object", "properties": {}},
        purity=Purity.PURE,
        determinism=Determinism.DETERMINISTIC,
        idempotency=Idempotency.IDEMPOTENT,
        reversibility=Reversibility.REVERSIBLE,
        side_effects=SideEffectScope.IN_MEMORY,
        concurrency_model=ConcurrencyModel.THREAD_SAFE,
        hardware_target=HardwareTarget.SIMD_AVX2,
        complexity=ComplexityCost(time="O(|Haystack| / SIMD_WIDTH)", space="O(1)"),
        preconditions=["len(input.needle) > 0"],
        postconditions=["is_strictly_ascending(output)"],
        compatible_adapters=["ADAPTER-OFFSET-TO-SPAN-OBS-16"],
    ),
    AlgorithmContract(
        id="ALGO-SRCH-11",
        name="SearchEngineAhoCorasickAlgo",
        version="1.2.0",
        category=AlgorithmCategory.SEARCH,
        capability_tags=["search.multipattern", "automaton.trie", "automaton.dfa"],
        input_schema={"type": "object", "required": ["text"], "properties": {"text": {"type": "string"}}},
        output_schema={
            "type": "array",
            "items": {
                "type": "object",
                "required": ["start_offset", "end_offset", "pattern"],
                "properties": {
                    "start_offset": {"type": "integer", "minimum": 0},
                    "end_offset": {"type": "integer", "minimum": 0},
                    "pattern": {"type": "string"},
                },
            },
        },
        parameters_schema={
            "type": "object",
            "required": ["patterns"],
            "properties": {
                "patterns": {"type": "array", "items": {"type": "string", "minLength": 1}, "minItems": 1}
            },
        },
        purity=Purity.PURE,
        determinism=Determinism.DETERMINISTIC,
        idempotency=Idempotency.IDEMPOTENT,
        reversibility=Reversibility.REVERSIBLE,
        side_effects=SideEffectScope.READ_ONLY,
        concurrency_model=ConcurrencyModel.THREAD_SAFE,
        hardware_target=HardwareTarget.CPU_SCALAR,
        complexity=ComplexityCost(time="O(|Text| + |Matches|)", space="O(TotalPatternChars)"),
        preconditions=["len(parameters.patterns) > 0", "all(len(p) > 0 for p in parameters.patterns)"],
        postconditions=["all(0 <= m.start_offset < m.end_offset <= len(input.text) for m in output)"],
        compatible_adapters=["ADAPTER-OFFSET-TO-SPAN-OBS-16", "ADAPTER-SNIPPET-WINDOW-SRCH-14"],
    ),
    AlgorithmContract(
        id="ALGO-SRCH-12",
        name="SearchEngineLazyDfaAlgo",
        version="1.0.0",
        category=AlgorithmCategory.SEARCH,
        capability_tags=["search.regex", "automaton.lazy_dfa", "regex.cached"],
        input_schema={
            "type": "object",
            "required": ["regex_pattern", "text"],
            "properties": {"regex_pattern": {"type": "string"}, "text": {"type": "string"}},
        },
        output_schema={
            "type": "array",
            "items": {
                "type": "object",
                "required": ["start", "end", "matched_text"],
                "properties": {"start": {"type": "integer"}, "end": {"type": "integer"}, "matched_text": {"type": "string"}},
            },
        },
        parameters_schema={"type": "object", "properties": {}},
        purity=Purity.PURE,
        determinism=Determinism.DETERMINISTIC,
        idempotency=Idempotency.IDEMPOTENT,
        reversibility=Reversibility.REVERSIBLE,
        side_effects=SideEffectScope.IN_MEMORY,
        concurrency_model=ConcurrencyModel.THREAD_SAFE,
        hardware_target=HardwareTarget.CPU_SCALAR,
        complexity=ComplexityCost(time="O(|Text|)", space="O(DFAStates)"),
        preconditions=["is_valid_regex(input.regex_pattern)"],
        postconditions=["all(m.start <= m.end for m in output)"],
        compatible_adapters=["ADAPTER-OFFSET-TO-SPAN-OBS-16"],
    ),
    AlgorithmContract(
        id="ALGO-SRCH-13",
        name="SearchEngineStreamingChunkScannerAlgo",
        version="1.0.0",
        category=AlgorithmCategory.SEARCH,
        capability_tags=["scanner.streaming", "buffer.sliding_window", "chunk.overlap"],
        input_schema={"type": "object", "required": ["file_path"], "properties": {"file_path": {"type": "string"}}},
        output_schema={"type": "array", "items": {"type": "object"}},
        parameters_schema={
            "type": "object",
            "properties": {
                "chunk_size": {"type": "integer", "default": 65536},
                "overlap_size": {"type": "integer", "default": 1024},
            },
        },
        purity=Purity.IMPURE,
        determinism=Determinism.DETERMINISTIC,
        idempotency=Idempotency.IDEMPOTENT,
        reversibility=Reversibility.REVERSIBLE,
        side_effects=SideEffectScope.READ_ONLY,
        concurrency_model=ConcurrencyModel.THREAD_SAFE,
        hardware_target=HardwareTarget.CPU_SCALAR,
        complexity=ComplexityCost(time="O(FileSize)", space="O(ChunkSize)"),
        preconditions=["parameters.overlap_size < parameters.chunk_size", "os.path.isfile(input.file_path)"],
        postconditions=["len(output) >= 0"],
        compatible_adapters=[],
    ),
    AlgorithmContract(
        id="ALGO-SRCH-14",
        name="SearchEngineContextSnippetCollectorAlgo",
        version="1.0.0",
        category=AlgorithmCategory.SEARCH,
        capability_tags=["formatter.snippet", "context.surrounding_lines", "ui.code_view"],
        input_schema={
            "type": "object",
            "required": ["lines", "target_line"],
            "properties": {
                "lines": {"type": "array", "items": {"type": "string"}},
                "target_line": {"type": "integer", "minimum": 1},
            },
        },
        output_schema={
            "type": "object",
            "required": ["start_line", "end_line", "formatted_snippet"],
            "properties": {
                "start_line": {"type": "integer"},
                "end_line": {"type": "integer"},
                "formatted_snippet": {"type": "string"},
                "raw_lines": {"type": "array", "items": {"type": "string"}},
            },
        },
        parameters_schema={
            "type": "object",
            "properties": {
                "before": {"type": "integer", "default": 2},
                "after": {"type": "integer", "default": 2},
            },
        },
        purity=Purity.PURE,
        determinism=Determinism.DETERMINISTIC,
        idempotency=Idempotency.IDEMPOTENT,
        reversibility=Reversibility.REVERSIBLE,
        side_effects=SideEffectScope.IN_MEMORY,
        concurrency_model=ConcurrencyModel.THREAD_SAFE,
        hardware_target=HardwareTarget.CPU_SCALAR,
        complexity=ComplexityCost(time="O(Before + After)", space="O(Before + After)"),
        preconditions=["1 <= input.target_line <= len(input.lines)"],
        postconditions=["output.start_line >= 1", "output.end_line <= len(input.lines)"],
        compatible_adapters=[],
    ),
    AlgorithmContract(
        id="ALGO-SRCH-15",
        name="SearchEngineMmapScannerAlgo",
        version="1.0.0",
        category=AlgorithmCategory.SEARCH,
        capability_tags=["scanner.mmap", "zero_copy.scan", "kernel.page_cache"],
        input_schema={
            "type": "object",
            "required": ["file_path", "pattern_bytes"],
            "properties": {"file_path": {"type": "string"}, "pattern_bytes": {"type": "string"}},
        },
        output_schema={"type": "array", "items": {"type": "integer"}},
        parameters_schema={"type": "object", "properties": {}},
        purity=Purity.IMPURE,
        determinism=Determinism.DETERMINISTIC,
        idempotency=Idempotency.IDEMPOTENT,
        reversibility=Reversibility.REVERSIBLE,
        side_effects=SideEffectScope.READ_ONLY,
        concurrency_model=ConcurrencyModel.THREAD_SAFE,
        hardware_target=HardwareTarget.MMAP_KERNEL,
        complexity=ComplexityCost(time="O(FileSize)", space="O(1)"),
        preconditions=["os.path.getsize(input.file_path) > 0"],
        postconditions=["is_strictly_ascending(output)"],
        compatible_adapters=["ADAPTER-OFFSET-TO-SPAN-OBS-16"],
    ),

    # -------------------------------------------------------------------------
    # OBSERVABILITY ALGORITHMS (16 - 21)
    # -------------------------------------------------------------------------
    AlgorithmContract(
        id="ALGO-OBS-16",
        name="PositionSpanTracker",
        version="1.0.0",
        category=AlgorithmCategory.OBSERVABILITY,
        capability_tags=["adapter.offset_to_line_col", "coordinate.converter", "bisect.line_index"],
        input_schema={
            "type": "object",
            "required": ["source_code", "start_offset", "end_offset"],
            "properties": {
                "source_code": {"type": "string"},
                "start_offset": {"type": "integer", "minimum": 0},
                "end_offset": {"type": "integer", "minimum": 0},
            },
        },
        output_schema={
            "type": "object",
            "required": ["start_line", "start_col", "end_line", "end_col", "byte_start", "byte_end"],
            "properties": {
                "start_line": {"type": "integer", "minimum": 1},
                "start_col": {"type": "integer", "minimum": 0},
                "end_line": {"type": "integer", "minimum": 1},
                "end_col": {"type": "integer", "minimum": 0},
                "byte_start": {"type": "integer"},
                "byte_end": {"type": "integer"},
            },
        },
        parameters_schema={"type": "object", "properties": {}},
        purity=Purity.PURE,
        determinism=Determinism.DETERMINISTIC,
        idempotency=Idempotency.IDEMPOTENT,
        reversibility=Reversibility.REVERSIBLE,
        side_effects=SideEffectScope.IN_MEMORY,
        concurrency_model=ConcurrencyModel.THREAD_SAFE,
        hardware_target=HardwareTarget.CPU_SCALAR,
        complexity=ComplexityCost(time="O(log Lines)", space="O(Lines)"),
        preconditions=["0 <= input.start_offset <= input.end_offset <= len(input.source_code)"],
        postconditions=["output.start_line <= output.end_line", "output.byte_start == input.start_offset"],
        compatible_adapters=["ADAPTER-SPAN-TO-CST-RANGE"],
    ),
    AlgorithmContract(
        id="ALGO-OBS-17",
        name="AstExtractor",
        version="1.0.0",
        category=AlgorithmCategory.OBSERVABILITY,
        capability_tags=["parser.ast", "ast.tree_extractor", "cst.visitor"],
        input_schema={
            "type": "object",
            "required": ["source_code"],
            "properties": {"source_code": {"type": "string"}, "filename": {"type": "string", "default": "<source>"}},
        },
        output_schema={
            "type": "array",
            "items": {
                "type": "object",
                "required": ["node_type", "name", "line_start", "line_end"],
                "properties": {
                    "node_type": {"type": "string"},
                    "name": {"type": "string"},
                    "line_start": {"type": "integer"},
                    "line_end": {"type": "integer"},
                    "docstring": {"type": "string", "nullable": True},
                    "decorators": {"type": "array", "items": {"type": "string"}},
                },
            },
        },
        parameters_schema={"type": "object", "properties": {}},
        purity=Purity.PURE,
        determinism=Determinism.DETERMINISTIC,
        idempotency=Idempotency.IDEMPOTENT,
        reversibility=Reversibility.REVERSIBLE,
        side_effects=SideEffectScope.IN_MEMORY,
        concurrency_model=ConcurrencyModel.THREAD_SAFE,
        hardware_target=HardwareTarget.CPU_SCALAR,
        complexity=ComplexityCost(time="O(|SourceCode|)", space="O(ASTNodes)"),
        preconditions=["len(input.source_code) >= 0"],
        postconditions=["all(n.line_start <= n.line_end for n in output)"],
        compatible_adapters=["ADAPTER-AST-TO-SCOPE-TREE", "ADAPTER-AST-TO-OUTLINE"],
    ),
    AlgorithmContract(
        id="ALGO-OBS-18",
        name="SymbolScopeResolver",
        version="1.0.0",
        category=AlgorithmCategory.OBSERVABILITY,
        capability_tags=["resolver.scope", "symbol.lexical_scope", "symbol.references"],
        input_schema={"type": "object", "required": ["source_code"], "properties": {"source_code": {"type": "string"}}},
        output_schema={
            "type": "object",
            "required": ["symbols"],
            "properties": {
                "symbols": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "required": ["name", "kind", "defined_line"],
                        "properties": {
                            "name": {"type": "string"},
                            "kind": {"type": "string"},
                            "defined_line": {"type": "integer"},
                            "references": {"type": "array", "items": {"type": "integer"}},
                        },
                    },
                }
            },
        },
        parameters_schema={"type": "object", "properties": {}},
        purity=Purity.PURE,
        determinism=Determinism.DETERMINISTIC,
        idempotency=Idempotency.IDEMPOTENT,
        reversibility=Reversibility.REVERSIBLE,
        side_effects=SideEffectScope.IN_MEMORY,
        concurrency_model=ConcurrencyModel.THREAD_SAFE,
        hardware_target=HardwareTarget.CPU_SCALAR,
        complexity=ComplexityCost(time="O(|AST|)", space="O(Symbols)"),
        preconditions=["len(input.source_code) >= 0"],
        postconditions=["len(output.symbols) >= 0"],
        compatible_adapters=["ADAPTER-SCOPE-TO-RENAME-PLAN"],
    ),
    AlgorithmContract(
        id="ALGO-OBS-19",
        name="CommentExtractor",
        version="1.0.0",
        category=AlgorithmCategory.OBSERVABILITY,
        capability_tags=["linter.comments", "doctrine.zero_inline", "comment.extractor"],
        input_schema={"type": "object", "required": ["source_code"], "properties": {"source_code": {"type": "string"}}},
        output_schema={
            "type": "object",
            "required": ["is_compliant", "total_comments", "banned_inline_comments"],
            "properties": {
                "is_compliant": {"type": "boolean"},
                "total_comments": {"type": "integer"},
                "banned_inline_comments": {"type": "array", "items": {"type": "object"}},
                "todos_and_fixmes": {"type": "array", "items": {"type": "object"}},
            },
        },
        parameters_schema={"type": "object", "properties": {}},
        purity=Purity.PURE,
        determinism=Determinism.DETERMINISTIC,
        idempotency=Idempotency.IDEMPOTENT,
        reversibility=Reversibility.REVERSIBLE,
        side_effects=SideEffectScope.IN_MEMORY,
        concurrency_model=ConcurrencyModel.THREAD_SAFE,
        hardware_target=HardwareTarget.CPU_SCALAR,
        complexity=ComplexityCost(time="O(|SourceCode|)", space="O(Comments)"),
        preconditions=["len(input.source_code) >= 0"],
        postconditions=["isinstance(output.is_compliant, bool)"],
        compatible_adapters=["ADAPTER-BANNED-COMMENTS-TO-PATCH"],
    ),
    AlgorithmContract(
        id="ALGO-OBS-20",
        name="ImportDependencyGrapher",
        version="1.0.0",
        category=AlgorithmCategory.OBSERVABILITY,
        capability_tags=["graph.imports", "dag.cycle_detector", "graph.topological_sort"],
        input_schema={
            "type": "object",
            "required": ["modules"],
            "properties": {
                "modules": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "required": ["name", "code"],
                        "properties": {"name": {"type": "string"}, "code": {"type": "string"}},
                    },
                }
            },
        },
        output_schema={
            "type": "object",
            "required": ["total_modules", "total_edges", "has_cycles", "topological_order"],
            "properties": {
                "total_modules": {"type": "integer"},
                "total_edges": {"type": "integer"},
                "has_cycles": {"type": "boolean"},
                "cycles": {"type": "array", "items": {"type": "array", "items": {"type": "string"}}},
                "topological_order": {"type": "array", "items": {"type": "string"}},
            },
        },
        parameters_schema={"type": "object", "properties": {}},
        purity=Purity.PURE,
        determinism=Determinism.DETERMINISTIC,
        idempotency=Idempotency.IDEMPOTENT,
        reversibility=Reversibility.REVERSIBLE,
        side_effects=SideEffectScope.IN_MEMORY,
        concurrency_model=ConcurrencyModel.THREAD_SAFE,
        hardware_target=HardwareTarget.CPU_SCALAR,
        complexity=ComplexityCost(time="O(V + E)", space="O(V + E)"),
        preconditions=["len(input.modules) > 0"],
        postconditions=["output.has_cycles == False ==> len(output.topological_order) == output.total_modules"],
        compatible_adapters=["ADAPTER-DAG-TO-EXECUTION-ORDER"],
    ),
    AlgorithmContract(
        id="ALGO-OBS-21",
        name="CodeOutlineGenerator",
        version="1.0.0",
        category=AlgorithmCategory.OBSERVABILITY,
        capability_tags=["outline.generator", "markdown.outline", "symbol.hierarchy"],
        input_schema={
            "type": "object",
            "required": ["file_path", "source_code"],
            "properties": {"file_path": {"type": "string"}, "source_code": {"type": "string"}},
        },
        output_schema={
            "type": "object",
            "required": ["total_lines", "symbols_count", "markdown"],
            "properties": {
                "total_lines": {"type": "integer"},
                "symbols_count": {"type": "integer"},
                "markdown": {"type": "string"},
            },
        },
        parameters_schema={"type": "object", "properties": {}},
        purity=Purity.PURE,
        determinism=Determinism.DETERMINISTIC,
        idempotency=Idempotency.IDEMPOTENT,
        reversibility=Reversibility.REVERSIBLE,
        side_effects=SideEffectScope.IN_MEMORY,
        concurrency_model=ConcurrencyModel.THREAD_SAFE,
        hardware_target=HardwareTarget.CPU_SCALAR,
        complexity=ComplexityCost(time="O(|SourceCode|)", space="O(Symbols)"),
        preconditions=["len(input.source_code) >= 0"],
        postconditions=["len(output.markdown) > 0"],
        compatible_adapters=[],
    ),

    # -------------------------------------------------------------------------
    # UPDATE ALGORITHMS (22 - 24)
    # -------------------------------------------------------------------------
    AlgorithmContract(
        id="ALGO-UPD-22",
        name="CstMatcher",
        version="1.0.0",
        category=AlgorithmCategory.UPDATE,
        capability_tags=["cst.matcher", "ast.whitespace_preserving", "refactoring.pattern_match"],
        input_schema={
            "type": "object",
            "required": ["source_code", "target_node_type"],
            "properties": {
                "source_code": {"type": "string"},
                "target_node_type": {"type": "string"},
                "pattern_filter": {"type": "object", "default": {}},
            },
        },
        output_schema={
            "type": "array",
            "items": {
                "type": "object",
                "required": ["start_line", "end_line", "start_col", "end_col", "original_text"],
                "properties": {
                    "start_line": {"type": "integer"},
                    "end_line": {"type": "integer"},
                    "start_col": {"type": "integer"},
                    "end_col": {"type": "integer"},
                    "original_text": {"type": "string"},
                    "node_name": {"type": "string", "nullable": True},
                },
            },
        },
        parameters_schema={"type": "object", "properties": {}},
        purity=Purity.PURE,
        determinism=Determinism.DETERMINISTIC,
        idempotency=Idempotency.IDEMPOTENT,
        reversibility=Reversibility.REVERSIBLE,
        side_effects=SideEffectScope.IN_MEMORY,
        concurrency_model=ConcurrencyModel.THREAD_SAFE,
        hardware_target=HardwareTarget.CPU_SCALAR,
        complexity=ComplexityCost(time="O(|SourceCode|)", space="O(Matches)"),
        preconditions=["len(input.source_code) >= 0"],
        postconditions=["all(m.start_line <= m.end_line for m in output)"],
        compatible_adapters=["ADAPTER-CST-MATCH-TO-PATCH-OP"],
    ),
    AlgorithmContract(
        id="ALGO-UPD-23",
        name="UpdateBatchPatcherAlgo",
        version="2.0.0",
        category=AlgorithmCategory.UPDATE,
        capability_tags=["patch.atomic", "update.filesystem", "safe.rollback", "sha256.precondition"],
        input_schema={
            "type": "object",
            "required": ["operations"],
            "properties": {
                "operations": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "required": ["file_path", "find_pattern", "replace_text"],
                        "properties": {
                            "file_path": {"type": "string"},
                            "find_pattern": {"type": "string"},
                            "replace_text": {"type": "string"},
                            "expected_sha256": {"type": "string", "nullable": True},
                            "is_regex": {"type": "boolean", "default": False},
                        },
                    },
                },
                "dry_run": {"type": "boolean", "default": False},
            },
        },
        output_schema={
            "type": "array",
            "items": {
                "type": "object",
                "required": ["file_path", "success", "before_sha256", "after_sha256"],
                "properties": {
                    "file_path": {"type": "string"},
                    "success": {"type": "boolean"},
                    "occurrences": {"type": "integer"},
                    "before_sha256": {"type": "string"},
                    "after_sha256": {"type": "string"},
                    "error_message": {"type": "string", "nullable": True},
                },
            },
        },
        parameters_schema={"type": "object", "properties": {}},
        purity=Purity.IMPURE,
        determinism=Determinism.DETERMINISTIC,
        idempotency=Idempotency.IDEMPOTENT,
        reversibility=Reversibility.REVERSIBLE,
        side_effects=SideEffectScope.DISK_WRITE,
        concurrency_model=ConcurrencyModel.PROCESS_ISOLATED,
        hardware_target=HardwareTarget.CPU_SCALAR,
        complexity=ComplexityCost(time="O(TotalFileSize)", space="O(MaxFileSize)"),
        preconditions=["all(os.path.exists(op.file_path) for op in input.operations)"],
        postconditions=["all(len(r.after_sha256) == 64 for r in output)"],
        compatible_adapters=[],
    ),
    AlgorithmContract(
        id="ALGO-UPD-24",
        name="UpdateDiffEngineAlgo",
        version="1.0.0",
        category=AlgorithmCategory.UPDATE,
        capability_tags=["diff.unified", "diff.gnu_git", "diff.line_counter"],
        input_schema={
            "type": "object",
            "required": ["original_content", "modified_content"],
            "properties": {
                "original_content": {"type": "string"},
                "modified_content": {"type": "string"},
                "file_path": {"type": "string", "default": "file"},
            },
        },
        output_schema={
            "type": "object",
            "required": ["file_path", "has_changes", "added_lines", "deleted_lines", "patch"],
            "properties": {
                "file_path": {"type": "string"},
                "has_changes": {"type": "boolean"},
                "added_lines": {"type": "integer"},
                "deleted_lines": {"type": "integer"},
                "patch": {"type": "string"},
            },
        },
        parameters_schema={"type": "object", "properties": {}},
        purity=Purity.PURE,
        determinism=Determinism.DETERMINISTIC,
        idempotency=Idempotency.IDEMPOTENT,
        reversibility=Reversibility.REVERSIBLE,
        side_effects=SideEffectScope.IN_MEMORY,
        concurrency_model=ConcurrencyModel.THREAD_SAFE,
        hardware_target=HardwareTarget.CPU_SCALAR,
        complexity=ComplexityCost(time="O(N * M)", space="O(N + M)"),
        preconditions=["isinstance(input.original_content, str)", "isinstance(input.modified_content, str)"],
        postconditions=["output.added_lines >= 0", "output.deleted_lines >= 0"],
        compatible_adapters=[],
    ),
]

BUILTIN_TYPE_ADAPTERS: List[TypeAdapterContract] = [
    TypeAdapterContract(
        id="ADAPTER-OFFSET-TO-SPAN-OBS-16",
        name="ByteOffsetToLineColSpanAdapter",
        source_type="ByteOffsets",
        target_type="PositionSpan",
        algo_id="ALGO-OBS-16",
        is_lossy=False,
        description="Converts raw byte search offsets to line-and-column position spans.",
    ),
    TypeAdapterContract(
        id="ADAPTER-SNIPPET-WINDOW-SRCH-14",
        name="MatchToContextSnippetAdapter",
        source_type="MatchPosition",
        target_type="ContextSnippet",
        algo_id="ALGO-SRCH-14",
        is_lossy=False,
        description="Extracts contextual code window around a match position.",
    ),
    TypeAdapterContract(
        id="ADAPTER-FILE-PATH-TO-CONTENT",
        name="FilePathToContentAdapter",
        source_type="FilePathList",
        target_type="FileContentMap",
        algo_id=None,
        is_lossy=False,
        description="Reads filesystem files into memory buffers.",
    ),
    TypeAdapterContract(
        id="ADAPTER-QUERY-TO-TRIGRAM-CANDIDATES",
        name="QueryToTrigramCandidatesAdapter",
        source_type="SearchQuery",
        target_type="CandidateDocIds",
        algo_id="ALGO-SRCH-09",
        is_lossy=True,
        description="Pre-filters documents with inverted 3-gram index.",
    ),
    TypeAdapterContract(
        id="ADAPTER-CST-MATCH-TO-PATCH-OP",
        name="CstMatchToPatchOperationAdapter",
        source_type="CstMatchList",
        target_type="PatchOperationList",
        algo_id="ALGO-UPD-22",
        is_lossy=False,
        description="Converts matched AST/CST nodes into atomic patch operations.",
    ),
]
