from __future__ import annotations

import math
from typing import Any, Dict, List, Literal, Optional, Sequence


class NnAlgoKlDivergenceLoss:
    """
    ---
    contract:
      algo_id: ALGO-NN-19
      name: NnAlgoKlDivergenceLoss
      version: 1.0.0
      category: nn
      capability_tags:
        - nn.loss
        - nn.information_theory
        - nn.kl_divergence
        - nn.distillation
      inputs:
        type: object
        properties:
          log_predictions:
            type: array
            items:
              type: array
              items:
                type: number
            description: Log-probabilities log Q of shape (B, C) generated by the student/model.
          target_probabilities:
            type: array
            items:
              type: array
              items:
                type: number
            description: Target probability distribution P of shape (B, C) from teacher/prior.
          log_target:
            type: boolean
            default: false
            description: Whether target_probabilities contains log P instead of P.
          reduction:
            type: string
            enum:
              - batchmean
              - mean
              - sum
              - none
            default: batchmean
            description: Reduction method across samples and classes.
        required:
          - log_predictions
          - target_probabilities
        additionalProperties: false
      outputs:
        type: object
        properties:
          loss:
            type: number
            description: Scalar reduced KL divergence loss.
          losses:
            type: array
            items:
              type: number
            description: Per-sample KL divergence values of length B (if reduction is none).
          gradients:
            type: array
            items:
              type: array
              items:
                type: number
            description: Analytic gradients dL/d(log Q) of shape (B, C).
        required:
          - gradients
        additionalProperties: false
    ---
    """

    @staticmethod
    def forward(
        log_predictions: Sequence[Sequence[float]],
        target_probabilities: Sequence[Sequence[float]],
        log_target: bool = False,
        reduction: Literal["batchmean", "mean", "sum", "none"] = "batchmean",
    ) -> Dict[str, Any]:
        b = len(log_predictions)
        if b == 0:
            raise ValueError("Precondition failed: log_predictions cannot be empty.")
        if len(target_probabilities) != b:
            raise ValueError(
                f"Precondition failed: targets length ({len(target_probabilities)}) must match predictions ({b})."
            )

        c = len(log_predictions[0])
        if c == 0:
            raise ValueError("Precondition failed: class dimension C cannot be zero.")

        sample_losses: List[float] = []
        grads: List[List[float]] = []

        for i in range(b):
            log_q = log_predictions[i]
            target_row = target_probabilities[i]
            if len(log_q) != c or len(target_row) != c:
                raise ValueError("Precondition failed: dimension mismatch in log_predictions or targets.")

            sample_kl = 0.0
            grad_row: List[float] = []

            for j in range(c):
                if log_target:
                    log_p_j = target_row[j]
                    p_j = math.exp(log_p_j)
                else:
                    p_j = target_row[j]
                    if p_j < 0.0:
                        raise ValueError(f"Precondition failed: probabilities must be non-negative, got {p_j}.")
                    log_p_j = math.log(p_j) if p_j > 1e-15 else -34.538776  # log(1e-15)

                log_q_j = log_q[j]

                # D_KL(P || Q) element: p_j * (log p_j - log q_j)
                if p_j > 0.0:
                    kl_elem = p_j * (log_p_j - log_q_j)
                else:
                    kl_elem = 0.0

                sample_kl += kl_elem
                # d(D_KL)/d(log q_j) = -p_j
                grad_row.append(-p_j)

            sample_losses.append(sample_kl)
            grads.append(grad_row)

        if reduction == "batchmean":
            scalar_loss = sum(sample_losses) / float(b)
            reduced_grads = [[g / float(b) for g in r] for r in grads]
            return {
                "loss": scalar_loss,
                "gradients": reduced_grads,
            }
        elif reduction == "mean":
            total_elements = float(b * c)
            scalar_loss = sum(sample_losses) / total_elements
            reduced_grads = [[g / total_elements for g in r] for r in grads]
            return {
                "loss": scalar_loss,
                "gradients": reduced_grads,
            }
        elif reduction == "sum":
            scalar_loss = sum(sample_losses)
            return {
                "loss": scalar_loss,
                "gradients": grads,
            }
        elif reduction == "none":
            return {
                "losses": sample_losses,
                "gradients": grads,
            }
        else:
            raise ValueError(f"Precondition failed: unrecognized reduction mode {reduction}")
