"""
================================================================================
ALGORITHM & ARCHITECTURE BLUEPRINT: BUILTIN DECLARATIVE AGENT CATALOG (22+ AGENTS)
================================================================================

1. OVERVIEW & OBJECTIVE:
   This module provides the declarative definitions of all standard specialized
   agents matching the 22 algorithms and 5 core pipeline roles from
   `policies/rules/edgeCases/algos/agent-operating-contract.md`.
   It allows instantiating and orchestrating specialized agents without code
   repetition, establishing a reusable template for scaling to 1000+ agents.

2. ARCHITECTURAL LAYOUT & DESIGN PILLARS:
   - Zero-Inline-Comment Doctrine: All agent metadata, algorithm mappings,
     role classifications, and tool bindings are articulated in this header block.
   - Declarative Immutability: Every agent manifest is an immutable frozen dataclass.
================================================================================
"""

from src.domain.ports.agent_manifest_port import AgentManifest, AgentRole

BUILTIN_AGENT_MANIFESTS = [
    # Core Pipeline Agents
    AgentManifest(
        agent_id="agent_scout",
        name="Scout Agent",
        role=AgentRole.SCOUT,
        category="core_pipeline",
        description="Scans repository files, filters paths, identifies targets, and executes fast structural discovery.",
        system_prompt="You are the Scout Agent. Enforce fast file enumeration, regex pattern matching, and AST token location.",
        allowed_tools=["search_codebase_ast", "search_policy_rules", "run_repo_audit"],
        algorithms=[1, 2, 3, 4, 5, 6, 7, 8],
        tags=["pipeline", "scout", "search"],
    ),
    AgentManifest(
        agent_id="agent_planner",
        name="Planner Agent",
        role=AgentRole.PLANNER,
        category="core_pipeline",
        description="Analyzes dependencies, computes SHA-256 precondition hashes, declares match counts, and builds change DAGs.",
        system_prompt="You are the Planner Agent. Plan safe, atomic code refactorings with precondition hashes and exact match expectations.",
        allowed_tools=["search_policy_rules", "generate_refactoring_plan"],
        algorithms=[9, 10, 11, 16, 21],
        tags=["pipeline", "planner", "dag"],
    ),
    AgentManifest(
        agent_id="agent_editor",
        name="Editor Agent",
        role=AgentRole.EDITOR,
        category="core_pipeline",
        description="Applies atomic AST modifications, extracts inline comments into top docblocks, and wraps API envelopes.",
        system_prompt="You are the Editor Agent. Apply verified AST modifications with zero inline comments and standard envelopes.",
        allowed_tools=["generate_refactoring_plan", "register_reusable_tool"],
        algorithms=[17, 18, 19, 20],
        tags=["pipeline", "editor", "refactor"],
    ),
    AgentManifest(
        agent_id="agent_verifier",
        name="Verifier Agent",
        role=AgentRole.VERIFIER,
        category="core_pipeline",
        description="Runs test suites, verifies invariant rules, cross-checks live standards, and ensures zero regression.",
        system_prompt="You are the Verifier Agent. Execute invariant audits, pytest suites, and live internet verification.",
        allowed_tools=["run_repo_audit", "search_internet_knowledge", "search_policy_rules"],
        algorithms=[12, 13, 14, 15],
        tags=["pipeline", "verifier", "test"],
    ),
    AgentManifest(
        agent_id="agent_reporter",
        name="Reporter Agent",
        role=AgentRole.REPORTER,
        category="core_pipeline",
        description="Generates structured diff summaries, OpenAPI changelogs, and metrics reports.",
        system_prompt="You are the Reporter Agent. Compile clean, verifiable audit and refactoring reports.",
        allowed_tools=["search_policy_rules"],
        algorithms=[14, 22],
        tags=["pipeline", "reporter", "summary"],
    ),

    # 22 Algorithm Specialized Agents
    AgentManifest(
        agent_id="algo_01_recursive_walk",
        name="Recursive Walk Agent",
        role=AgentRole.SCOUT,
        category="file_discovery",
        description="DFS directory subtree scanner with depth bounding and early subtree pruning.",
        system_prompt="Execute deterministic recursive file walk with ignore-list pre-filtering.",
        allowed_tools=["search_codebase_ast"],
        algorithms=[1],
        tags=["algo", "walk", "filesystem"],
    ),
    AgentManifest(
        agent_id="algo_02_work_stealing_walker",
        name="Work-Stealing Walker Agent",
        role=AgentRole.SCOUT,
        category="file_discovery",
        description="Parallel work-stealing directory traverser for massive monorepos.",
        system_prompt="Execute multi-threaded lock-free directory traversal.",
        allowed_tools=["search_codebase_ast"],
        algorithms=[2],
        tags=["algo", "parallel", "walker"],
    ),
    AgentManifest(
        agent_id="algo_03_git_aware_walker",
        name="Git-Aware Walker Agent",
        role=AgentRole.SCOUT,
        category="file_discovery",
        description="Fast index reader scanning tracked files and respecting .gitignore rules.",
        system_prompt="Enumerate git tracked files and check working tree dirty states.",
        allowed_tools=["search_codebase_ast"],
        algorithms=[3],
        tags=["algo", "git", "gitignore"],
    ),
    AgentManifest(
        agent_id="algo_04_glob_matcher",
        name="Glob Matcher Agent",
        role=AgentRole.SCOUT,
        category="file_discovery",
        description="Compiled prefix/suffix trie and double-star glob matcher.",
        system_prompt="Match file paths against path allowlists and denylists.",
        allowed_tools=["search_codebase_ast"],
        algorithms=[4],
        tags=["algo", "glob", "filter"],
    ),
    AgentManifest(
        agent_id="algo_05_binary_classifier",
        name="Binary/Text Classifier Agent",
        role=AgentRole.SCOUT,
        category="file_discovery",
        description="Null-byte and UTF-8 validity scanner guarding against binary file mutations.",
        system_prompt="Classify files as UTF-8 text or binary to prevent corruption.",
        allowed_tools=["search_codebase_ast"],
        algorithms=[5],
        tags=["algo", "binary", "encoding"],
    ),
    AgentManifest(
        agent_id="algo_06_content_type_prober",
        name="Content-Type Prober Agent",
        role=AgentRole.SCOUT,
        category="file_discovery",
        description="Magic byte signature and shebang line detector.",
        system_prompt="Probe file headers to identify programming languages and formats.",
        allowed_tools=["search_codebase_ast"],
        algorithms=[6],
        tags=["algo", "magic_bytes", "shebang"],
    ),
    AgentManifest(
        agent_id="algo_07_size_line_bouncer",
        name="Size & Line Bouncer Agent",
        role=AgentRole.SCOUT,
        category="file_discovery",
        description="Size cap and line count limiter preventing memory exhaustion on huge files.",
        system_prompt="Enforce file size limits and line count caps.",
        allowed_tools=["search_codebase_ast"],
        algorithms=[7],
        tags=["algo", "size_limit", "guardrail"],
    ),
    AgentManifest(
        agent_id="algo_08_generated_code_classifier",
        name="Generated Code Classifier Agent",
        role=AgentRole.SCOUT,
        category="file_discovery",
        description="Header token scanner identifying generated files (protobuf, openapi, mocks) to skip.",
        system_prompt="Identify autogenerated files and exclude them from manual refactoring.",
        allowed_tools=["search_codebase_ast"],
        algorithms=[8],
        tags=["algo", "generated_code", "classifier"],
    ),
    AgentManifest(
        agent_id="algo_09_trigram_index",
        name="Trigram Index Agent",
        role=AgentRole.PLANNER,
        category="pattern_search",
        description="N-gram inverted index for sub-millisecond regex candidate retrieval.",
        system_prompt="Query 3-gram index for instantaneous symbol and pattern location.",
        allowed_tools=["search_codebase_ast"],
        algorithms=[9],
        tags=["algo", "trigram", "indexing"],
    ),
    AgentManifest(
        agent_id="algo_10_simd_memchr",
        name="SIMD Literal Scanner Agent",
        role=AgentRole.SCOUT,
        category="pattern_search",
        description="Vectorized byte matcher for exact string scanning.",
        system_prompt="Scan large source buffers using SIMD literal search.",
        allowed_tools=["search_codebase_ast"],
        algorithms=[10],
        tags=["algo", "simd", "memchr"],
    ),
    AgentManifest(
        agent_id="algo_11_aho_corasick",
        name="Aho-Corasick Multi-Pattern Agent",
        role=AgentRole.PLANNER,
        category="pattern_search",
        description="Finite state machine trie searching hundreds of invariant keywords in one pass.",
        system_prompt="Search multi-keyword violation lists simultaneously in O(N).",
        allowed_tools=["search_codebase_ast", "run_repo_audit"],
        algorithms=[11],
        tags=["algo", "aho_corasick", "multi_pattern"],
    ),
    AgentManifest(
        agent_id="algo_12_lazy_dfa",
        name="Lazy DFA Regex Agent",
        role=AgentRole.VERIFIER,
        category="pattern_search",
        description="On-demand state transition regex engine with zero exponential backtracking.",
        system_prompt="Execute complex regular expressions with linear time guarantees.",
        allowed_tools=["search_codebase_ast"],
        algorithms=[12],
        tags=["algo", "regex", "dfa"],
    ),
    AgentManifest(
        agent_id="algo_13_streaming_chunk_scanner",
        name="Streaming Chunk Scanner Agent",
        role=AgentRole.VERIFIER,
        category="pattern_search",
        description="Sliding window boundary scanner handling multi-line cross-chunk matches.",
        system_prompt="Scan multi-gigabyte repositories using bounded sliding buffers.",
        allowed_tools=["search_codebase_ast"],
        algorithms=[13],
        tags=["algo", "streaming", "sliding_window"],
    ),
    AgentManifest(
        agent_id="algo_14_context_snippet_collector",
        name="Context Snippet Collector Agent",
        role=AgentRole.REPORTER,
        category="pattern_search",
        description="Surrounding line collector formatting syntax-highlighted issue snippets.",
        system_prompt="Collect contextual lines around detected invariant violations.",
        allowed_tools=["search_codebase_ast"],
        algorithms=[14],
        tags=["algo", "snippets", "formatting"],
    ),
    AgentManifest(
        agent_id="algo_15_mmap_scanner",
        name="Memory-Mapped IO Scanner Agent",
        role=AgentRole.SCOUT,
        category="pattern_search",
        description="Zero-copy virtual memory scanner for extreme search throughput.",
        system_prompt="Read files via memory-mapped buffers with zero user-space allocations.",
        allowed_tools=["search_codebase_ast"],
        algorithms=[15],
        tags=["algo", "mmap", "zero_copy"],
    ),
    AgentManifest(
        agent_id="algo_16_position_span_tracker",
        name="Position & Span Tracker Agent",
        role=AgentRole.PLANNER,
        category="pattern_search",
        description="Byte offset to line/column indexer computing exact replacement spans.",
        system_prompt="Compute exact line, column, and byte spans for clean AST replacements.",
        allowed_tools=["search_codebase_ast"],
        algorithms=[16],
        tags=["algo", "spans", "byte_offsets"],
    ),
    AgentManifest(
        agent_id="algo_17_tree_sitter_ast",
        name="Tree-Sitter AST Scanner Agent",
        role=AgentRole.EDITOR,
        category="structural_ast",
        description="Grammar-based parser building concrete syntax trees across languages.",
        system_prompt="Parse code into concrete syntax trees and match structural query nodes.",
        allowed_tools=["search_codebase_ast", "generate_refactoring_plan"],
        algorithms=[17],
        tags=["algo", "ast", "tree_sitter"],
    ),
    AgentManifest(
        agent_id="algo_18_cst_matcher",
        name="Concrete Syntax Tree Matcher Agent",
        role=AgentRole.EDITOR,
        category="structural_ast",
        description="Lossless CST matcher preserving comments, whitespace, and formatting.",
        system_prompt="Execute lossless code refactorings preserving exact surrounding whitespace.",
        allowed_tools=["generate_refactoring_plan"],
        algorithms=[18],
        tags=["algo", "cst", "lossless"],
    ),
    AgentManifest(
        agent_id="algo_19_symbol_scope_resolver",
        name="Symbol Scope Resolver Agent",
        role=AgentRole.EDITOR,
        category="structural_ast",
        description="Lexical environment and symbol shadow resolver preventing scope conflicts.",
        system_prompt="Track variable scopes, closures, and shadows during variable renames.",
        allowed_tools=["search_codebase_ast", "generate_refactoring_plan"],
        algorithms=[19],
        tags=["algo", "scope", "symbol_table"],
    ),
    AgentManifest(
        agent_id="algo_20_comment_extractor",
        name="Comment & Docstring Extractor Agent",
        role=AgentRole.EDITOR,
        category="structural_ast",
        description="Inline comment classifier extracting mid-function comments into top docblocks.",
        system_prompt="Extract all function-body inline comments and format into top-side blueprints.",
        allowed_tools=["generate_refactoring_plan"],
        algorithms=[20],
        tags=["algo", "comments", "zero_inline_doctrine"],
    ),
    AgentManifest(
        agent_id="algo_21_import_dependency_grapher",
        name="Import & Dependency Grapher Agent",
        role=AgentRole.PLANNER,
        category="structural_ast",
        description="Module import resolver detecting cyclic dependencies and computing DAG orders.",
        system_prompt="Analyze import statements, detect circular dependencies, and order changes.",
        allowed_tools=["search_codebase_ast", "search_policy_rules"],
        algorithms=[21],
        tags=["algo", "dependency_graph", "dag"],
    ),
    AgentManifest(
        agent_id="algo_22_code_outline_generator",
        name="Code Outline Generator Agent",
        role=AgentRole.REPORTER,
        category="structural_ast",
        description="Hierarchical symbol and class outline generator for high-level codebase maps.",
        system_prompt="Generate hierarchical outlines of classes, methods, and exported types.",
        allowed_tools=["search_codebase_ast"],
        algorithms=[22],
        tags=["algo", "outline", "symbol_map"],
    ),
]
