"""
Code Engine Algorithms Root Package
"""

from src.features.code_engine.algos.search import (
    SearchEngineRecursiveWalkAlgo,
    SearchEngineWorkStealingWalkerAlgo,
    SearchEngineGitAwareWalkerAlgo,
    SearchEngineGlobMatcherAlgo,
    SearchEngineTrigramIndexAlgo,
    SearchEngineSimdMemchrAlgo,
    SearchEngineAhoCorasickAlgo,
    SearchEngineLazyDfaAlgo,
    SearchEngineStreamingChunkScannerAlgo,
    SearchEngineContextSnippetCollectorAlgo,
    SearchEngineMmapScannerAlgo,
)

from src.features.code_engine.algos.classifier import (
    ClassifierAlgoBinaryClassifier,
    SearchEngineBinaryClassifierAlgo,
    ClassifierAlgoGeneratedCode,
    SearchEngineGeneratedCodeClassifierAlgo,
    ClassifierAlgoContentTypeProber,
    SearchEngineContentTypeProberAlgo,
    ClassifierAlgoSizeLineBouncer,
    SearchEngineSizeLineBouncerAlgo,
)

from src.features.code_engine.algos.transform import (
    TransformAlgoBurrowsWheeler,
    SearchEngineBurrowsWheelerTransformAlgo,
    TransformAlgoDeltaGapEncoding,
    SearchEngineDeltaGapEncodingAlgo,
    TransformAlgoVarintEncoding,
    SearchEngineVarintEncodingAlgo,
    TransformAlgoBitPackingPforDelta,
    SearchEngineBitPackingPforDeltaAlgo,
    TransformAlgoEliasFano,
    SearchEngineEliasFanoAlgo,
    TransformAlgoLcpArrayKasai,
    SearchEngineLcpArrayKasaiAlgo,
    TransformAlgoAstChunking,
    SearchEngineAstChunkingAlgo,
    TransformAlgoBooleanQuerySimplifier,
    SearchEngineBooleanQuerySimplifierAlgo,
    TransformAlgoReverseInnerOptimizer,
    SearchEngineReverseInnerOptimizerAlgo,
    TransformAlgoRegexToTrigramQuery,
    SearchEngineRegexToTrigramQueryAlgo,
    TransformAlgoLiteralExtraction,
    SearchEngineLiteralExtractionAlgo,
)

from src.features.code_engine.algos.observability import (
    PositionSpanTracker,
    PositionSpan,
    AstExtractor,
    AstNode,
    SymbolScopeResolver,
    Symbol,
    LexicalScope,
    CommentExtractor,
    ExtractedComment,
    CommentLintResult,
    ImportDependencyGrapher,
    ImportNode,
    DependencyGraphReport,
    CodeOutlineGenerator,
    OutlineSymbol,
    FileOutline,
)

from src.features.code_engine.algos.update import (
    CstMatcher,
    CstMatch,
    UpdateBatchPatcherAlgo,
    PatchOperation,
    PatchResult,
    UpdateDiffEngineAlgo,
    UnifiedDiffResult,
)

from src.features.code_engine.algos.vector import (
    VectorAlgoL2Normalization,
    VectorAlgoMeanCentering,
    VectorAlgoLayerNorm,
    VectorAlgoMinMaxZScore,
    VectorAlgoMatryoshkaSlicing,
    VectorAlgoScalarQuantization,
    QuantizedVector,
    VectorAlgoBinaryQuantization,
    VectorAlgoTokenPooling,
    VectorAlgoSemanticChunker,
    TextChunk,
)

from src.features.code_engine.algos.graph import (
    GraphAlgoBfsTraversal,
    GraphAlgoDfsTraversal,
    GraphAlgoDijkstraShortestPath,
    GraphAlgoAstarSearch,
    GraphAlgoPageRankCentrality,
    GraphAlgoDegreeCentrality,
    GraphAlgoConnectedComponents,
    GraphAlgoTarjanScc,
    GraphAlgoSubgraphIsomorphism,
)

from src.features.code_engine.algos.vector_filter import (
    VectorFilterAlgoPreFilter,
    VectorFilterAlgoPostFilter,
    VectorFilterAlgoInGraphFilter,
    VectorFilterAlgoSelectivityPlanner,
    VectorFilterAlgoPartitionedIndex,
)

from src.features.code_engine.algos.buffer import (
    CodeEngineGapBufferAlgo,
    CodeEngineRopeAlgo,
    CodeEnginePieceTableAlgo,
    CodeEngineLineIndexAlgo,
    CodeEngineUndoRedoStackAlgo,
    CodeEngineTextEditAlgo,
    CodeEngineWorkspaceEditAlgo,
    CodeEnginePositionEncodingAlgo,
    CodeEngineReverseOrderEditAlgo,
    CodeEngineIntervalTreeAlgo,
    CodeEngineEditRebasingAlgo,
    CodeEngineIdempotentEditsAlgo,
)

from src.features.code_engine.algos.diff import (
    CodeEngineLcsDpDiffAlgo,
    CodeEngineMyersDiffAlgo,
    CodeEngineLinearMyersDiffAlgo,
    CodeEnginePatienceDiffAlgo,
    CodeEngineHistogramDiffAlgo,
    CodeEngineLineHashingInterningAlgo,
    CodeEngineUnifiedDiffAlgo,
    CodeEngineSearchReplaceBlockAlgo,
    CodeEngineWordCharRefinementAlgo,
    CodeEngineThreeWayMergeAlgo,
    CodeEngineFuzzyPatchAlgo,
)

from src.features.code_engine.algos.syntax_mutation import (
    CodeEngineLosslessSyntaxTreeAlgo,
    CodeEngineRedGreenTreeAlgo,
    CodeEngineTriviaAttachmentAlgo,
    CodeEngineTreeRewriterAlgo,
    CodeEngineSemanticPatchAlgo,
    CodeEngineImportManagerAlgo,
    CodeEngineRenameRefactoringAlgo,
)

from src.features.code_engine.algos.atomic_mutation import (
    CodeEngineDryRunPlannerAlgo,
    CodeEngineCasContentHashAlgo,
    CodeEngineWriteAheadJournalAlgo,
    CodeEngineSagaCompensatorAlgo,
    CodeEngineFileIdentityPreserverAlgo,
    CodeEngineBuildGraphAffectedAlgo,
    CodeEnginePostConditionSearchAlgo,
    CodeEngineExactReplaceUniqueAlgo,
    CodeEngineErrorFeedbackRetryAlgo,
    CodeEngineSynthesizedCodemodsAlgo,
    CodeEngineSpeculativeEditsAlgo,
    CodeEngineScratchpadProgressAlgo,
    CodeEngineHumanCheckpointAlgo,
    CodeEnginePermissionSandboxAlgo,
)

__all__ = [
    # Search
    "SearchEngineRecursiveWalkAlgo",
    "SearchEngineWorkStealingWalkerAlgo",
    "SearchEngineGitAwareWalkerAlgo",
    "SearchEngineGlobMatcherAlgo",
    "SearchEngineTrigramIndexAlgo",
    "SearchEngineSimdMemchrAlgo",
    "SearchEngineAhoCorasickAlgo",
    "SearchEngineLazyDfaAlgo",
    "SearchEngineStreamingChunkScannerAlgo",
    "SearchEngineContextSnippetCollectorAlgo",
    "SearchEngineMmapScannerAlgo",
    # Classifier
    "ClassifierAlgoBinaryClassifier",
    "SearchEngineBinaryClassifierAlgo",
    "ClassifierAlgoGeneratedCode",
    "SearchEngineGeneratedCodeClassifierAlgo",
    "ClassifierAlgoContentTypeProber",
    "SearchEngineContentTypeProberAlgo",
    "ClassifierAlgoSizeLineBouncer",
    "SearchEngineSizeLineBouncerAlgo",
    # Transform
    "TransformAlgoBurrowsWheeler",
    "SearchEngineBurrowsWheelerTransformAlgo",
    "TransformAlgoDeltaGapEncoding",
    "SearchEngineDeltaGapEncodingAlgo",
    "TransformAlgoVarintEncoding",
    "SearchEngineVarintEncodingAlgo",
    "TransformAlgoBitPackingPforDelta",
    "SearchEngineBitPackingPforDeltaAlgo",
    "TransformAlgoEliasFano",
    "SearchEngineEliasFanoAlgo",
    "TransformAlgoLcpArrayKasai",
    "SearchEngineLcpArrayKasaiAlgo",
    "TransformAlgoAstChunking",
    "SearchEngineAstChunkingAlgo",
    "TransformAlgoBooleanQuerySimplifier",
    "SearchEngineBooleanQuerySimplifierAlgo",
    "TransformAlgoReverseInnerOptimizer",
    "SearchEngineReverseInnerOptimizerAlgo",
    "TransformAlgoRegexToTrigramQuery",
    "SearchEngineRegexToTrigramQueryAlgo",
    "TransformAlgoLiteralExtraction",
    "SearchEngineLiteralExtractionAlgo",
    # Buffer
    "CodeEngineGapBufferAlgo",
    "CodeEngineRopeAlgo",
    "CodeEnginePieceTableAlgo",
    "CodeEngineLineIndexAlgo",
    "CodeEngineUndoRedoStackAlgo",
    "CodeEngineTextEditAlgo",
    "CodeEngineWorkspaceEditAlgo",
    "CodeEnginePositionEncodingAlgo",
    "CodeEngineReverseOrderEditAlgo",
    "CodeEngineIntervalTreeAlgo",
    "CodeEngineEditRebasingAlgo",
    "CodeEngineIdempotentEditsAlgo",
    # Diff
    "CodeEngineLcsDpDiffAlgo",
    "CodeEngineMyersDiffAlgo",
    "CodeEngineLinearMyersDiffAlgo",
    "CodeEnginePatienceDiffAlgo",
    "CodeEngineHistogramDiffAlgo",
    "CodeEngineLineHashingInterningAlgo",
    "CodeEngineUnifiedDiffAlgo",
    "CodeEngineSearchReplaceBlockAlgo",
    "CodeEngineWordCharRefinementAlgo",
    "CodeEngineThreeWayMergeAlgo",
    "CodeEngineFuzzyPatchAlgo",
    # Syntax Mutation
    "CodeEngineLosslessSyntaxTreeAlgo",
    "CodeEngineRedGreenTreeAlgo",
    "CodeEngineTriviaAttachmentAlgo",
    "CodeEngineTreeRewriterAlgo",
    "CodeEngineSemanticPatchAlgo",
    "CodeEngineImportManagerAlgo",
    "CodeEngineRenameRefactoringAlgo",
    # Atomic Mutation
    "CodeEngineDryRunPlannerAlgo",
    "CodeEngineCasContentHashAlgo",
    "CodeEngineWriteAheadJournalAlgo",
    "CodeEngineSagaCompensatorAlgo",
    "CodeEngineFileIdentityPreserverAlgo",
    "CodeEnginePostConditionSearchAlgo",
    "CodeEngineExactReplaceUniqueAlgo",
    # Observability
    "PositionSpanTracker",
    "PositionSpan",
    "AstExtractor",
    "AstNode",
    "SymbolScopeResolver",
    "Symbol",
    "LexicalScope",
    "CommentExtractor",
    "ExtractedComment",
    "CommentLintResult",
    "ImportDependencyGrapher",
    "ImportNode",
    "DependencyGraphReport",
    "CodeOutlineGenerator",
    "OutlineSymbol",
    "FileOutline",
    # Update
    "CstMatcher",
    "CstMatch",
    "UpdateBatchPatcherAlgo",
    "PatchOperation",
    "PatchResult",
    "UpdateDiffEngineAlgo",
    "UnifiedDiffResult",
    # Vector
    "VectorAlgoL2Normalization",
    "VectorAlgoMeanCentering",
    "VectorAlgoLayerNorm",
    "VectorAlgoMinMaxZScore",
    "VectorAlgoMatryoshkaSlicing",
    "VectorAlgoScalarQuantization",
    "QuantizedVector",
    "VectorAlgoBinaryQuantization",
    "VectorAlgoTokenPooling",
    "VectorAlgoSemanticChunker",
    "TextChunk",
    # Graph
    "GraphAlgoBfsTraversal",
    "GraphAlgoDfsTraversal",
    "GraphAlgoDijkstraShortestPath",
    "GraphAlgoAstarSearch",
    "GraphAlgoPageRankCentrality",
    "GraphAlgoDegreeCentrality",
    "GraphAlgoConnectedComponents",
    "GraphAlgoTarjanScc",
    "GraphAlgoSubgraphIsomorphism",
    # Vector Filter
    "VectorFilterAlgoPreFilter",
    "VectorFilterAlgoPostFilter",
    "VectorFilterAlgoInGraphFilter",
    "VectorFilterAlgoSelectivityPlanner",
    "VectorFilterAlgoPartitionedIndex",
]
