"""
Search Engine Algorithms Root Package
"""

from src.features.code_engine.algos.search import (
    SearchEngineRecursiveWalkAlgo,
    SearchEngineWorkStealingWalkerAlgo,
    SearchEngineGitAwareWalkerAlgo,
    SearchEngineGlobMatcherAlgo,
    SearchEngineBinaryClassifierAlgo,
    SearchEngineContentTypeProberAlgo,
    SearchEngineSizeLineBouncerAlgo,
    SearchEngineGeneratedCodeClassifierAlgo,
    SearchEngineTrigramIndexAlgo,
    SearchEngineSimdMemchrAlgo,
    SearchEngineAhoCorasickAlgo,
    SearchEngineLazyDfaAlgo,
    SearchEngineStreamingChunkScannerAlgo,
    SearchEngineContextSnippetCollectorAlgo,
    SearchEngineMmapScannerAlgo,
)

from src.features.code_engine.algos.observability import (
    PositionSpanTracker,
    PositionSpan,
    AstExtractor,
    AstNode,
    SymbolScopeResolver,
    Symbol,
    LexicalScope,
    CommentExtractor,
    ExtractedComment,
    CommentLintResult,
    ImportDependencyGrapher,
    ImportNode,
    DependencyGraphReport,
    CodeOutlineGenerator,
    OutlineSymbol,
    FileOutline,
)

from src.features.code_engine.algos.update import (
    CstMatcher,
    CstMatch,
    UpdateBatchPatcherAlgo,
    PatchOperation,
    PatchResult,
    UpdateDiffEngineAlgo,
    UnifiedDiffResult,
)

__all__ = [
    "SearchEngineRecursiveWalkAlgo",
    "SearchEngineWorkStealingWalkerAlgo",
    "SearchEngineGitAwareWalkerAlgo",
    "SearchEngineGlobMatcherAlgo",
    "SearchEngineBinaryClassifierAlgo",
    "SearchEngineContentTypeProberAlgo",
    "SearchEngineSizeLineBouncerAlgo",
    "SearchEngineGeneratedCodeClassifierAlgo",
    "SearchEngineTrigramIndexAlgo",
    "SearchEngineSimdMemchrAlgo",
    "SearchEngineAhoCorasickAlgo",
    "SearchEngineLazyDfaAlgo",
    "SearchEngineStreamingChunkScannerAlgo",
    "SearchEngineContextSnippetCollectorAlgo",
    "SearchEngineMmapScannerAlgo",
    "PositionSpanTracker",
    "PositionSpan",
    "AstExtractor",
    "AstNode",
    "SymbolScopeResolver",
    "Symbol",
    "LexicalScope",
    "CommentExtractor",
    "ExtractedComment",
    "CommentLintResult",
    "ImportDependencyGrapher",
    "ImportNode",
    "DependencyGraphReport",
    "CodeOutlineGenerator",
    "OutlineSymbol",
    "FileOutline",
    "CstMatcher",
    "CstMatch",
    "UpdateBatchPatcherAlgo",
    "PatchOperation",
    "PatchResult",
    "UpdateDiffEngineAlgo",
    "UnifiedDiffResult",
]
