"""
Code Engine Algorithms Root Package
"""

from src.features.code_engine.algos.search import (
    SearchEngineRecursiveWalkAlgo,
    SearchEngineWorkStealingWalkerAlgo,
    SearchEngineGitAwareWalkerAlgo,
    SearchEngineGlobMatcherAlgo,
    SearchEngineTrigramIndexAlgo,
    SearchEngineSimdMemchrAlgo,
    SearchEngineAhoCorasickAlgo,
    SearchEngineLazyDfaAlgo,
    SearchEngineStreamingChunkScannerAlgo,
    SearchEngineContextSnippetCollectorAlgo,
    SearchEngineMmapScannerAlgo,
)

from src.features.code_engine.algos.classifier import (
    ClassifierAlgoBinaryClassifier,
    SearchEngineBinaryClassifierAlgo,
    ClassifierAlgoGeneratedCode,
    SearchEngineGeneratedCodeClassifierAlgo,
    ClassifierAlgoContentTypeProber,
    SearchEngineContentTypeProberAlgo,
    ClassifierAlgoSizeLineBouncer,
    SearchEngineSizeLineBouncerAlgo,
)

from src.features.code_engine.algos.transform import (
    TransformAlgoBurrowsWheeler,
    SearchEngineBurrowsWheelerTransformAlgo,
    TransformAlgoDeltaGapEncoding,
    SearchEngineDeltaGapEncodingAlgo,
    TransformAlgoVarintEncoding,
    SearchEngineVarintEncodingAlgo,
    TransformAlgoBitPackingPforDelta,
    SearchEngineBitPackingPforDeltaAlgo,
    TransformAlgoEliasFano,
    SearchEngineEliasFanoAlgo,
    TransformAlgoLcpArrayKasai,
    SearchEngineLcpArrayKasaiAlgo,
    TransformAlgoAstChunking,
    SearchEngineAstChunkingAlgo,
    TransformAlgoBooleanQuerySimplifier,
    SearchEngineBooleanQuerySimplifierAlgo,
    TransformAlgoReverseInnerOptimizer,
    SearchEngineReverseInnerOptimizerAlgo,
    TransformAlgoRegexToTrigramQuery,
    SearchEngineRegexToTrigramQueryAlgo,
    TransformAlgoLiteralExtraction,
    SearchEngineLiteralExtractionAlgo,
)

from src.features.code_engine.algos.observability import (
    PositionSpanTracker,
    PositionSpan,
    AstExtractor,
    AstNode,
    SymbolScopeResolver,
    Symbol,
    LexicalScope,
    CommentExtractor,
    ExtractedComment,
    CommentLintResult,
    ImportDependencyGrapher,
    ImportNode,
    DependencyGraphReport,
    CodeOutlineGenerator,
    OutlineSymbol,
    FileOutline,
)

from src.features.code_engine.algos.update import (
    CstMatcher,
    CstMatch,
    UpdateBatchPatcherAlgo,
    PatchOperation,
    PatchResult,
    UpdateDiffEngineAlgo,
    UnifiedDiffResult,
)

from src.features.code_engine.algos.vector import (
    VectorAlgoL2Normalization,
    VectorAlgoMeanCentering,
    VectorAlgoLayerNorm,
    VectorAlgoMinMaxZScore,
    VectorAlgoMatryoshkaSlicing,
    VectorAlgoScalarQuantization,
    QuantizedVector,
    VectorAlgoBinaryQuantization,
    VectorAlgoTokenPooling,
    VectorAlgoSemanticChunker,
    TextChunk,
)

from src.features.code_engine.algos.graph import (
    GraphAlgoBfsTraversal,
    GraphAlgoDfsTraversal,
    GraphAlgoDijkstraShortestPath,
    GraphAlgoAstarSearch,
    GraphAlgoPageRankCentrality,
    GraphAlgoDegreeCentrality,
    GraphAlgoConnectedComponents,
    GraphAlgoTarjanScc,
    GraphAlgoSubgraphIsomorphism,
)

from src.features.code_engine.algos.vector_filter import (
    VectorFilterAlgoPreFilter,
    VectorFilterAlgoPostFilter,
    VectorFilterAlgoInGraphFilter,
    VectorFilterAlgoSelectivityPlanner,
    VectorFilterAlgoPartitionedIndex,
)

__all__ = [
    # Search
    "SearchEngineRecursiveWalkAlgo",
    "SearchEngineWorkStealingWalkerAlgo",
    "SearchEngineGitAwareWalkerAlgo",
    "SearchEngineGlobMatcherAlgo",
    "SearchEngineTrigramIndexAlgo",
    "SearchEngineSimdMemchrAlgo",
    "SearchEngineAhoCorasickAlgo",
    "SearchEngineLazyDfaAlgo",
    "SearchEngineStreamingChunkScannerAlgo",
    "SearchEngineContextSnippetCollectorAlgo",
    "SearchEngineMmapScannerAlgo",
    # Classifier
    "ClassifierAlgoBinaryClassifier",
    "SearchEngineBinaryClassifierAlgo",
    "ClassifierAlgoGeneratedCode",
    "SearchEngineGeneratedCodeClassifierAlgo",
    "ClassifierAlgoContentTypeProber",
    "SearchEngineContentTypeProberAlgo",
    "ClassifierAlgoSizeLineBouncer",
    "SearchEngineSizeLineBouncerAlgo",
    # Transform
    "TransformAlgoBurrowsWheeler",
    "SearchEngineBurrowsWheelerTransformAlgo",
    "TransformAlgoDeltaGapEncoding",
    "SearchEngineDeltaGapEncodingAlgo",
    "TransformAlgoVarintEncoding",
    "SearchEngineVarintEncodingAlgo",
    "TransformAlgoBitPackingPforDelta",
    "SearchEngineBitPackingPforDeltaAlgo",
    "TransformAlgoEliasFano",
    "SearchEngineEliasFanoAlgo",
    "TransformAlgoLcpArrayKasai",
    "SearchEngineLcpArrayKasaiAlgo",
    "TransformAlgoAstChunking",
    "SearchEngineAstChunkingAlgo",
    "TransformAlgoBooleanQuerySimplifier",
    "SearchEngineBooleanQuerySimplifierAlgo",
    "TransformAlgoReverseInnerOptimizer",
    "SearchEngineReverseInnerOptimizerAlgo",
    "TransformAlgoRegexToTrigramQuery",
    "SearchEngineRegexToTrigramQueryAlgo",
    "TransformAlgoLiteralExtraction",
    "SearchEngineLiteralExtractionAlgo",
    # Observability
    "PositionSpanTracker",
    "PositionSpan",
    "AstExtractor",
    "AstNode",
    "SymbolScopeResolver",
    "Symbol",
    "LexicalScope",
    "CommentExtractor",
    "ExtractedComment",
    "CommentLintResult",
    "ImportDependencyGrapher",
    "ImportNode",
    "DependencyGraphReport",
    "CodeOutlineGenerator",
    "OutlineSymbol",
    "FileOutline",
    # Update
    "CstMatcher",
    "CstMatch",
    "UpdateBatchPatcherAlgo",
    "PatchOperation",
    "PatchResult",
    "UpdateDiffEngineAlgo",
    "UnifiedDiffResult",
    # Vector
    "VectorAlgoL2Normalization",
    "VectorAlgoMeanCentering",
    "VectorAlgoLayerNorm",
    "VectorAlgoMinMaxZScore",
    "VectorAlgoMatryoshkaSlicing",
    "VectorAlgoScalarQuantization",
    "QuantizedVector",
    "VectorAlgoBinaryQuantization",
    "VectorAlgoTokenPooling",
    "VectorAlgoSemanticChunker",
    "TextChunk",
    # Graph
    "GraphAlgoBfsTraversal",
    "GraphAlgoDfsTraversal",
    "GraphAlgoDijkstraShortestPath",
    "GraphAlgoAstarSearch",
    "GraphAlgoPageRankCentrality",
    "GraphAlgoDegreeCentrality",
    "GraphAlgoConnectedComponents",
    "GraphAlgoTarjanScc",
    "GraphAlgoSubgraphIsomorphism",
    # Vector Filter
    "VectorFilterAlgoPreFilter",
    "VectorFilterAlgoPostFilter",
    "VectorFilterAlgoInGraphFilter",
    "VectorFilterAlgoSelectivityPlanner",
    "VectorFilterAlgoPartitionedIndex",
]
