import json
import subprocess
import pytest
from src.features.code_engine.registry.algorithm_catalog import BUILTIN_ALGORITHM_CONTRACTS


def test_cli_all_42_algorithms_execute():
    test_inputs = {
        "ALGO-SRCH-01": {"root_dir": "src/features"},
        "ALGO-SRCH-02": {"root_dir": "src/features"},
        "ALGO-SRCH-03": {"root_dir": "src/features"},
        "ALGO-SRCH-04": {"pattern": "*.py", "file_paths": ["test.py", "main.rs"]},
        "ALGO-SRCH-05": {"file_path": "pyproject.toml"},
        "ALGO-SRCH-06": {"file_path": "pyproject.toml"},
        "ALGO-SRCH-07": {"file_path": "pyproject.toml", "max_bytes": 1000000},
        "ALGO-SRCH-08": {"file_path": "pyproject.toml"},
        "ALGO-SRCH-09": {"text": "algorithm inverted index test"},
        "ALGO-SRCH-10": {"data": "hello\nworld\ntest\n", "byte": "\n"},
        "ALGO-SRCH-11": {"text": "the quick brown fox", "patterns": ["quick", "fox"]},
        "ALGO-SRCH-12": {"text": "user@example.com", "pattern": r"user@example\.com"},
        "ALGO-SRCH-13": {"file_path": "pyproject.toml", "needle": "policy"},
        "ALGO-SRCH-14": {"text": "line1\nline2 target\nline3", "match_offset": 6},
        "ALGO-SRCH-15": {"file_path": "pyproject.toml", "needle": "name"},
        "ALGO-OBS-16": {"content": "alpha\nbeta\ngamma", "offset": 7},
        "ALGO-OBS-17": {"code": "def foo():\n    return 42", "language": "python"},
        "ALGO-OBS-18": {"code": "x = 10\ndef bar():\n    y = 20\n    return x + y"},
        "ALGO-OBS-19": {"code": "def clean():\n    return 1"},
        "ALGO-OBS-20": {"file_paths": ["src/api/rest/app.py"]},
        "ALGO-OBS-21": {"code": "class Sample:\n    def method(self):\n        pass"},
        "ALGO-UPD-22": {"code": "x = old_fn()", "pattern": "old_fn", "replacement": "new_fn"},
        "ALGO-UPD-23": {"file_path": "/tmp/test_patch.txt", "patches": []},
        "ALGO-UPD-24": {"original_content": "line1\nline2", "modified_content": "line1\nline2_mod"},
        "ALGO-VEC-01": {"vector": [3.0, 4.0]},
        "ALGO-VEC-02": {"vectors": [[1.0, 2.0], [3.0, 4.0]]},
        "ALGO-VEC-03": {"vector": [1.0, 2.0, 3.0, 4.0]},
        "ALGO-VEC-04": {"vector": [1.0, 5.0, 10.0]},
        "ALGO-VEC-05": {"vector": [float(i) for i in range(128)], "target_dim": 32},
        "ALGO-VEC-06": {"vector": [0.1, -0.5, 0.9, -0.2], "bits": 8},
        "ALGO-VEC-07": {"vector": [0.5, -0.2, 0.8, -0.9]},
        "ALGO-VEC-08": {"token_embeddings": [[1.0, 2.0], [3.0, 4.0]]},
        "ALGO-VEC-09": {"text": "Hello world from vector semantic chunker.", "max_chunk_size": 50, "overlap": 10},
        "ALGO-GRAPH-01": {"adjacency_list": {"A": ["B", "C"], "B": ["D"], "C": [], "D": []}, "start_node": "A"},
        "ALGO-GRAPH-02": {"adjacency_list": {"A": ["B", "C"], "B": ["D"], "C": [], "D": []}, "start_node": "A"},
        "ALGO-GRAPH-03": {"weighted_edges": [{"source": "A", "target": "B", "weight": 1.0}], "start_node": "A", "target_node": "B"},
        "ALGO-GRAPH-04": {"weighted_edges": [{"source": "A", "target": "B", "weight": 1.0}], "start_node": "A", "target_node": "B"},
        "ALGO-GRAPH-05": {"adjacency_list": {"A": ["B"], "B": ["A"]}},
        "ALGO-GRAPH-06": {"adjacency_list": {"A": ["B"], "B": ["A"]}},
        "ALGO-GRAPH-07": {"edges": [["A", "B"], ["C", "D"]]},
        "ALGO-GRAPH-08": {"adjacency_list": {"A": ["B"], "B": ["A"]}},
        "ALGO-GRAPH-09": {"target_graph": {"1": ["2"], "2": []}, "pattern_graph": {"A": ["B"], "B": []}},
        "ALGO-VEC-SRCH-51": {"database_vectors": [[1.0, 0.0], [0.0, 1.0]], "query_vectors": [[1.0, 0.0]], "k": 2},
        "ALGO-VEC-SRCH-52": {"vector_a": [1.0, 2.0], "vector_b": [1.0, 3.0], "metric": "l2"},
        "ALGO-VEC-SRCH-53": {"candidates": [{"id": "1", "score": 5.0}], "k": 1},
        "ALGO-VEC-SRCH-54": {"scores": [1.0, 5.0, 2.0], "k": 2},
        "ALGO-VEC-SRCH-55": {"database_vectors": [[0.0, 0.0], [1.0, 1.0]], "query_vector": [0.0, 0.0], "k": 1},
        "ALGO-VEC-SRCH-56": {"database_vectors": [[0.0, 0.0], [1.0, 1.0]], "pivots": [[0.0, 0.0]], "query_vector": [0.1, 0.1], "k": 1},
        "ALGO-VEC-SRCH-57": {"vectors": [[1.0, 2.0], [3.0, 4.0]], "query": [1.0, 2.0], "k": 1},
        "ALGO-VEC-SRCH-58": {"vectors": [[1.0, 2.0], [3.0, 4.0]], "query": [1.0, 2.0], "k": 1},
        "ALGO-VEC-SRCH-59": {"vectors": [[1.0, 2.0], [3.0, 4.0]], "query": [1.0, 2.0], "k": 1},
        "ALGO-VEC-SRCH-60": {"vectors": [[1.0, 2.0], [3.0, 4.0]], "query": [1.0, 2.0], "k": 1, "num_trees": 2},
        "ALGO-VEC-SRCH-61": {"vectors": [[1.0, 2.0], [3.0, 4.0], [5.0, 6.0], [7.0, 8.0]], "query": [1.0, 2.0], "k": 1, "num_clusters": 2},
        "ALGO-VEC-SRCH-62": {"vectors": [[1.0, 2.0], [3.0, 4.0], [5.0, 6.0], [7.0, 8.0]], "query": [1.0, 2.0], "k": 1, "num_clusters": 2, "subspaces": 2, "codebook_size": 2},
        "ALGO-VEC-SRCH-63": {"database_vectors": [[1.0, 2.0], [3.0, 4.0]], "sample_queries": [[1.0, 2.0]], "k": 1, "num_clusters": 2},
        "ALGO-VEC-SRCH-64": {"vectors": [[1.0, 2.0], [3.0, 4.0], [5.0, 6.0], [7.0, 8.0]], "query": [1.0, 2.0], "k": 1, "codebook_k1": 2, "codebook_k2": 2},
        "ALGO-VEC-SRCH-65": {"vectors": [[0.0, 0.0], [1.0, 0.0], [0.0, 1.0], [10.0, 10.0]], "query": [0.1, 0.1], "k": 2, "max_edges": 3},
        "ALGO-VEC-SRCH-66": {"vectors": [[0.0, 0.0], [1.0, 0.0]], "layers": [{"0": [1], "1": [0]}], "entry_point": 0, "top_layer": 0, "query": [0.1, 0.0], "k": 1, "ef": 4},
        "ALGO-VEC-SRCH-67": {"vectors": [[0.0, 0.0], [1.0, 0.0], [0.0, 1.0]], "m": 2, "ef_construction": 4},
        "ALGO-VEC-SRCH-68": {"vectors": [[0.0, 0.0], [1.0, 0.0], [2.0, 0.0]], "adjacency": {"0": [1], "1": [0, 2], "2": [1]}, "start_nodes": [0], "query": [1.1, 0.0], "k": 1, "ef": 4},
        "ALGO-VEC-SRCH-69": {"vectors": [[0.0, 0.0], [1.0, 0.0], [0.0, 1.0]], "query": [0.1, 0.1], "k": 2, "r_max_degree": 2, "l_search_list_size": 4, "alpha": 1.2},
        "ALGO-VEC-SRCH-70": {"point": [0.0, 0.0], "candidate_vectors": [[1.0, 0.0], [0.0, 1.0]], "alpha": 1.2, "r_max_degree": 2},
        "ALGO-VEC-SRCH-71": {"vectors": [[0.0, 0.0], [1.0, 0.0], [0.0, 1.0]], "query": [0.1, 0.1], "k": 2, "r_max_degree": 2},
        "ALGO-VEC-SRCH-72": {"vectors": [[0.0, 0.0], [1.0, 0.0], [0.0, 1.0], [1.0, 1.0]], "query": [0.1, 0.1], "k": 2, "fixed_degree": 2},
        "ALGO-VEC-SRCH-73": {"vectors": [[0.0, 0.0], [1.0, 1.0]], "strategy": "medoid"},
        "ALGO-VEC-SRCH-74": {"vectors": [[0.0, 0.0], [1.0, 0.0]], "adjacency": {"0": [1], "1": [0]}, "entry_points": [0]},
        "ALGO-VEC-SRCH-75": {"vectors": [[0.0, 0.0], [1.0, 0.0]], "labels": ["t1", "t2"], "query": [0.0, 0.0], "target_label": "t1", "k": 1},
        "ALGO-VEC-SRCH-76": {"vectors": [[0.0, 0.0], [1.0, 0.0], [2.0, 0.0]], "query": [0.0, 0.0], "k": 1, "num_centroids": 2, "nprobe": 1, "slack_factor": 1.2},
        "ALGO-VEC-SRCH-77": {"vectors": [[1.0, 0.0], [0.0, 1.0]], "query": [1.0, 0.0], "k": 1, "num_bits": 2, "num_tables": 2},
        "ALGO-VEC-SRCH-78": {"vectors": [[1.0, 0.0], [0.0, 1.0]], "query": [1.0, 0.0], "k": 1, "num_bits": 2, "probe_budget": 2},
        "ALGO-VEC-SRCH-79": {"vectors": [[0.0, 0.0], [1.0, 1.0]], "query": [0.0, 0.0], "k": 1, "slot_width_w": 2.0, "num_projections_m": 2, "num_tables_l": 2},
        "ALGO-VEC-FLTR-80": {"vectors": [[0.0, 0.0], [1.0, 1.0]], "metadata": [{"tenant": "alpha"}, {"tenant": "beta"}], "query": [0.1, 0.1], "filters": {"tenant": "alpha"}, "k": 1},
        "ALGO-VEC-FLTR-81": {"vectors": [[0.0, 0.0], [1.0, 1.0]], "metadata": [{"lang": "en"}, {"lang": "fr"}], "query": [0.1, 0.1], "filters": {"lang": "en"}, "k": 1, "oversample_factor": 2.0},
        "ALGO-VEC-FLTR-82": {"vectors": [[0.0, 0.0], [1.0, 0.0]], "metadata": [{"status": "active"}, {"status": "inactive"}], "adjacency": {"0": [1], "1": []}, "entry_point": 0, "query": [0.9, 0.0], "filters": {"status": "active"}, "k": 1, "ef_search": 4},
        "ALGO-VEC-FLTR-83": {"total_vectors": 1000, "metadata_sample": [{"tenant": "T1"}, {"tenant": "T2"}], "filters": {"tenant": "T1"}, "is_security_filter": True},
        "ALGO-VEC-FLTR-84": {"partitions": {"tenant_A": [{"id": "d1", "vector": [1.0, 0.0], "metadata": {}}]}, "target_partition": "tenant_A", "query": [0.9, 0.1], "k": 1},
        "ALGO-VEC-SRCH-85": {"corpus": ["the quick brown fox"], "query": "fox", "k": 1},
        "ALGO-VEC-SRCH-86": {"dense_results": [{"id": "1", "score": 0.9}], "sparse_results": [{"id": "1", "score": 10.0}], "alpha": 0.5, "k": 1},
        "ALGO-VEC-SRCH-87": {"rankings": [[{"id": "doc1"}], [{"id": "doc1"}]], "k_rrf": 60, "top_k": 1},
        "ALGO-VEC-SRCH-88": {"score_lists": [[{"id": "doc1", "score": 0.9}]], "weights": [1.0], "top_k": 1},
        "ALGO-VEC-SRCH-89": {"candidate_vectors": [[1.0, 0.0]], "candidate_ids": ["1"], "query_vector": [1.0, 0.0], "lambda_mult": 0.5, "k": 1},
        "ALGO-VEC-SRCH-90": {"vectors": [[0.0, 0.0]], "query": [0.0, 0.0], "radius": 1.0, "metric": "l2", "max_results": 1},
        "ALGO-VEC-SRCH-91": {"document_token_vectors": [[[1.0, 0.0]]], "query_token_vectors": [[1.0, 0.0]], "k": 1},
        "ALGO-VEC-SRCH-92": {"vectors": [[1.0, 0.0]], "expanded_queries": [[1.0, 0.0]], "k": 1, "aggregation": "max"},
        "ALGO-VEC-SRCH-93": {"candidate_ids": [0], "full_precision_vectors": [[1.0, 0.0]], "query_vector": [1.0, 0.0], "metric": "l2", "top_k": 1},
        "ALGO-VEC-SRCH-94": {"query": "test", "candidates": [{"id": "1", "text": "test document"}], "top_k": 1},
        "ALGO-VEC-SRCH-95": {"stage1_candidates": [{"id": "1", "score": 1.0}], "stage2_top_m": 1, "stage3_top_k": 1},
        "ALGO-VEC-SRCH-96": {"query": "test", "candidates": [{"id": "1", "text": "doc"}], "simulated_llm_response": "[0]", "top_k": 1},
        "ALGO-VEC-SRCH-97": {"corpus_vectors": [[1.0, 0.0]], "query_vector": [1.0, 0.0], "hypothetical_vectors": [[1.0, 0.0]], "k": 1, "query_weight": 0.5},
        "ALGO-VEC-SRCH-98": {"query": "def parse():", "available_routes": ["lexical_bm25", "dense_vector"]},
        "ALGO-VEC-SRCH-99": {"shard_results": [[{"id": "doc1", "score": 1.0}]], "top_k": 1},
        "ALGO-VEC-SRCH-100": {"centroids": [[1.0, 0.0]], "centroid_to_shard_map": {"0": "shard1"}, "query_vector": [1.0, 0.0], "num_target_shards": 1},
        "ALGO-VEC-SRCH-101": {"replicas": [{"id": "rep1", "is_healthy": True, "active_connections": 1}], "strategy": "least_loaded", "counter": 0},
        "ALGO-VEC-SRCH-102": {"primary_latency_ms": 10.0, "backup_latency_ms": 5.0, "hedge_delay_threshold_ms": 2.0, "is_read_only": True},
        "ALGO-VEC-SRCH-103": {"shard_sorted_lists": [[{"id": "doc1", "score": 0.9}]], "k": 1},
        "ALGO-VEC-SRCH-104": {"cache_store": {}, "query": "q", "tenant_id": "t1", "filters": {}, "index_version": "v1", "results": [{"id": "1"}], "ttl_seconds": 3600.0, "max_size": 1000},
        "ALGO-VEC-SRCH-105": {"cached_entries": [{"id": "e1", "vector": [1.0, 0.0], "tenant_id": "t1", "response": "resp"}], "query_vector": [1.0, 0.0], "tenant_id": "t1", "similarity_threshold": 0.9},
        "ALGO-VEC-SRCH-106": {"pending_queries": [{"id": "q1"}], "max_batch_size": 2, "max_latency_ms": 10.0},
        "ALGO-VEC-SRCH-107": {"components": [{"name": "c1", "size_mb": 10, "access_priority": 1}], "ram_budget_mb": 100.0},
        "ALGO-VEC-SRCH-108": {"requested_node_ids": [1], "cached_nodes": [], "page_size_bytes": 4096, "bytes_per_node": 128, "max_batch_size": 16},
        "ALGO-VEC-SRCH-109": {"current_tokens": 10.0, "max_tokens": 100.0, "refill_rate_per_sec": 10.0, "last_refill_timestamp": 0.0, "current_concurrency": 1, "max_concurrency": 10, "request_cost": 1.0, "now": 1.0},
        "ALGO-VEC-SRCH-110": {"ground_truth_topk": [[1]], "parameter_evaluations": [{"parameters": {"ef": 16}, "retrieved_topk": [[1]], "latency_ms": 1.0}], "target_recall": 0.8},
        "ALGO-VEC-TRFM-01": {"text": "unbelievable tokenization test", "vocab": {"un": 1, "believ": 2, "able": 3, "token": 4, "ization": 5, "test": 6}},
        "ALGO-VEC-TRFM-02": {"token_ids": [101, 2054, 102], "hidden_dim": 16},
        "ALGO-VEC-TRFM-03": {"token_embeddings": [[1.0, 2.0], [3.0, 4.0]], "attention_mask": [1, 1]},
        "ALGO-VEC-TRFM-04": {"token_embeddings": [[1.0, 2.0], [3.0, 4.0]]},
        "ALGO-VEC-TRFM-05": {"token_embeddings": [[1.0, 2.0], [3.0, 4.0]], "attention_mask": [1, 1]},
        "ALGO-VEC-TRFM-06": {"text": "what is vector search?", "task_type": "query"},
        "ALGO-VEC-TRFM-07": {"query_vectors": [[1.0, 0.0]], "document_vectors": [[0.9, 0.1], [0.0, 1.0]]},
        "ALGO-VEC-TRFM-08": {"candidates": [{"id": "d1", "similarity": 0.88}, {"id": "d2", "similarity": 0.5}], "positive_ids": ["d2"]},
        "ALGO-VEC-TRFM-09": {"vector": [0.1, 0.2, 0.3, 0.4, 0.5, 0.6], "nested_dims": [2, 4]},
        "ALGO-VEC-TRFM-10": {"token_embeddings": [[1.0, 0.0], [0.0, 1.0], [1.0, 1.0]], "chunk_spans": [[0, 2], [2, 3]]},
        "ALGO-VEC-TRFM-11": {"tokens": ["token1", "token2", "token3", "token4", "token5"], "window_size": 3, "overlap": 1},
        "ALGO-VEC-TRFM-12": {"sentences": ["First sentence here.", "Second sentence follows.", "Third sentence about cars."], "sentence_embeddings": [[1.0, 0.0], [0.95, 0.05], [0.0, 1.0]]},
        "ALGO-VEC-TRFM-13": {"text": "Paragraph one.\n\nParagraph two is slightly longer.", "chunk_size": 20},
        "ALGO-VEC-TRFM-14": {"token_sequences": [[1, 2, 3], [4, 5]], "batch_size": 2},
        "ALGO-VEC-TRFM-15": {"vector": [3.0, 4.0]},
        "ALGO-VEC-TRFM-16": {"vectors": [[2.0, 4.0], [4.0, 6.0]]},
        "ALGO-VEC-TRFM-17": {"vectors": [[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]]},
        "ALGO-VEC-TRFM-18": {"vectors": [[10.0, 1.0], [10.2, 2.0], [9.8, 0.5]], "num_components_to_remove": 1},
        "ALGO-VEC-TRFM-19": {"database_vectors": [[1.0, 2.0], [3.0, 4.0]], "query_vector": [1.0, 1.0]},
        "ALGO-VEC-TRFM-20": {"scores": [0.9, 0.5, 0.1], "method": "temperature"},
        "ALGO-VEC-TRFM-21": {"query_vectors": [[1.0, 0.0]], "candidate_vectors": [[0.9, 0.1], [0.1, 0.9]]},
        "ALGO-VEC-TRFM-22": {"source_anchors": [[1.0, 0.0], [0.0, 1.0]], "target_anchors": [[0.0, 1.0], [-1.0, 0.0]]},
        "ALGO-VEC-TRFM-23": {"vectors": [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]], "target_dim": 2},
        "ALGO-VEC-TRFM-24": {"vectors": [[1.0, 0.0, 2.0], [0.0, 3.0, 0.0], [4.0, 0.0, 5.0]], "n_components": 2},
        "ALGO-VEC-TRFM-25": {"vectors": [[1.0, 2.0, 3.0, 4.0]], "target_dim": 2},
        "ALGO-VEC-TRFM-26": {"vectors": [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]], "bottleneck_dim": 2},
        "ALGO-VEC-TRFM-27": {"vectors": [[1.0, 0.0], [0.9, 0.1], [0.0, 1.0], [0.1, 0.9]], "n_components": 2, "n_neighbors": 2},
        "ALGO-VEC-TRFM-28": {"vectors": [[1.0, 2.0], [1.1, 2.1], [5.0, 5.0], [5.1, 5.1]], "n_components": 2, "perplexity": 2.0},
        "ALGO-VEC-TRFM-29": {"vector": [1.0, 2.0, 3.0, 4.0]},
        "ALGO-VEC-TRFM-30": {"batch_vectors": [[1.0, 2.0], [3.0, 4.0]], "target_dim": 1},
        "ALGO-VEC-TRFM-31": {"vector": [0.5, -0.2, 0.8], "num_bits": 16},
        "ALGO-VEC-TRFM-32": {"token_embeddings": [[0.1, 0.8, -0.3]]},
        "ALGO-VEC-TRFM-33": {"vector": [-1.0, 0.0, 0.5, 1.0], "bits": 8},
        "ALGO-VEC-TRFM-34": {"vector": [0.5, -0.2, 0.8, -0.9]},
        "ALGO-VEC-TRFM-35": {"vector": [1.0, 2.0, 3.0, 4.0], "m_subspaces": 2},
        "ALGO-VEC-TRFM-36": {"vector": [1.0, 2.0, 3.0, 4.0], "m_subspaces": 2},
        "ALGO-VEC-TRFM-37": {"vector": [1.0, 2.0, 3.0, 4.0], "num_stages": 2},
        "ALGO-VEC-TRFM-38": {"vector": [1.0, 2.0, 3.0, 4.0]},
        "ALGO-VEC-TRFM-39": {"vectors": [[0.0, 0.0], [1.0, 1.0], [5.0, 5.0], [6.0, 6.0]], "k_clusters": 2},
        "ALGO-VEC-TRFM-40": {"vectors": [[0.0, 0.0], [1.0, 1.0], [5.0, 5.0], [6.0, 6.0]], "k_clusters": 2},
        "ALGO-VEC-TRFM-41": {"vectors": [[0.0, 0.0], [1.0, 1.0], [10.0, 10.0], [11.0, 11.0]], "k_clusters": 2, "batch_size": 2},
        "ALGO-VEC-TRFM-42": {"vectors": [[0.0, 0.0], [1.0, 1.0], [5.0, 5.0], [6.0, 6.0]], "branching_factor": 2, "max_depth": 1},
        "ALGO-VEC-TRFM-43": {"query_vector": [1.0, 2.0], "codebooks": [[[0.0], [1.0]], [[0.0], [2.0]]], "candidate_pq_codes": [[1, 1], [0, 0]]},
        "ALGO-VEC-TRFM-44": {"query_vector": [1.0, 2.0, 3.0, 4.0], "candidate_codes": [[0, 1], [1, 0]], "subspace_dim": 2},
        "ALGO-VEC-TRFM-45": {"vector": [1.2, -0.8, 3.4]},
        "ALGO-VEC-TRFM-46": {"vector": [1.0, -2.5, 0.003], "dtype_target": "float16"},
        "ALGO-VEC-TRFM-47": {"tokens": ["hello", "world"], "token_embeddings": [[1.0, 0.0], [0.0, 1.0]]},
        "ALGO-VEC-TRFM-48": {"token_vectors": [[1.0, 0.0], [0.99, 0.01], [0.0, 1.0]]},
        "ALGO-VEC-TRFM-49": {"term_weights": {"vector": 0.8, "search": 0.5}},
        "ALGO-VEC-TRFM-50": {"cache_store": {}, "text": "sample text query", "vector_to_cache": [0.1, 0.2]},
        "ALGO-VEC-UPD-111": {"source_id": "doc1", "chunk_id": "c0", "model_version": "1.0.0", "content": "Sample content text", "metadata": {"author": "admin"}},
        "ALGO-VEC-UPD-112": {"operations": [{"op_type": "UPSERT", "record_id": "r1", "vector": [0.1, 0.2]}], "last_sequence_num": 0},
        "ALGO-VEC-UPD-113": {"buffer_records": [], "new_records": [{"id": "r1", "vector": [0.1, 0.2]}], "max_buffer_size": 1000, "query_vector": [0.1, 0.2]},
        "ALGO-VEC-UPD-114": {"segments": [{"segment_id": "s1", "records": [{"id": "r1", "vector": [0.1, 0.2]}], "tombstone_ids": []}], "query_vector": [0.1, 0.2], "top_k": 5},
        "ALGO-VEC-UPD-115": {"segments_to_merge": [{"segment_id": "s1", "records": [{"id": "r1", "vector": [0.1, 0.2]}], "tombstone_ids": ["r1"]}], "target_tier": "L1"},
        "ALGO-VEC-UPD-116": {"active_tombstones": ["r1"], "delete_ids": ["r2"], "candidate_ids": ["r1", "r2", "r3"], "total_index_size": 100},
        "ALGO-VEC-UPD-117": {"adjacency_list": {"n1": ["n2", "n3"], "n2": ["n1"], "n3": ["n1"]}, "deleted_nodes": ["n1"]},
        "ALGO-VEC-UPD-118": {"disk_graph_nodes": ["d1", "d2"], "mem_graph_nodes": ["m1"], "deleted_nodes": [], "new_records": ["m2"], "mem_threshold": 500},
        "ALGO-VEC-UPD-119": {"centroids": [[0.0, 0.0], [1.0, 1.0]], "vectors_to_insert": [{"id": "v1", "vector": [0.1, 0.2]}], "inverted_lists": {}},
        "ALGO-VEC-UPD-120": {"baseline_quantization_error": 0.05, "current_quantization_error": 0.08, "inverted_list_lengths": [10, 15, 20]},
        "ALGO-VEC-UPD-121": {"total_chunks": 1000, "completed_chunks": 250, "elapsed_seconds": 50.0, "target_model_version": "v2.0"},
        "ALGO-VEC-UPD-122": {"mutation_events": [{"record_id": "r1", "op_type": "UPSERT"}], "primary_ids": [], "shadow_ids": []},
        "ALGO-VEC-UPD-123": {"current_alias_target": "blue", "candidate_target": "green", "is_candidate_warmed": True},
        "ALGO-VEC-UPD-124": {"incoming_chunks": [{"chunk_id": "c1", "content": "text"}], "stored_hash_map": {}},
        "ALGO-VEC-UPD-125": {"cdc_raw_events": [{"key": "k1", "op": "INSERT", "log_offset": 100}], "partition_count": 4},
        "ALGO-VEC-UPD-126": {"pending_outbox_rows": [{"event_id": "e1", "retry_count": 0}], "published_event_ids": []},
        "ALGO-VEC-UPD-127": {"source_records": [{"id": "r1", "hash": "h1"}], "target_records": [{"id": "r1", "hash": "h1"}]},
        "ALGO-VEC-UPD-128": {"stage_watermarks": {"cdc": 100.0, "embed": 98.0, "index": 95.0}, "current_time": 102.0},
        "ALGO-VEC-UPD-129": {"record_id": "r1", "incoming_version": 2, "idempotency_token": "tok1", "stored_version": 1},
        "ALGO-VEC-UPD-130": {"job_id": "j1", "last_cursor": "cur1", "processed_count": 50, "total_count": 100, "last_item_id": "item50"},
        "ALGO-VEC-UPD-131": {"incoming_items": [{"id": "1"}, {"id": "2"}], "max_batch_size": 2},
        "ALGO-VEC-UPD-132": {"queue_items": [{"type": "DELETE", "id": "d1"}, {"type": "BACKFILL", "id": "b1"}], "drain_limit": 10},
        "ALGO-VEC-UPD-133": {"active_versions": [{"version_id": "v1", "commit_seq": 10}], "pinned_version_ids": ["v1"]},
        "ALGO-VEC-UPD-134": {"consistency_level": "READ_YOUR_WRITES", "replica_sequence_num": 100, "client_write_token_seq": 100},
        "ALGO-VEC-UPD-135": {"leader_sequence_num": 100, "followers": [{"replica_id": "f1", "sequence_num": 100}]},
        "ALGO-VEC-UPD-136": {"current_term": 1, "cluster_size": 3, "vote_responses": [{"vote_granted": True, "term": 1}, {"vote_granted": True, "term": 1}]},
        "ALGO-VEC-UPD-137": {"total_replicas_n": 3, "write_ack_count_w": 2, "read_responses": [{"version": 2, "replica_id": "r1"}, {"version": 1, "replica_id": "r2"}]},
        "ALGO-VEC-UPD-138": {"snapshot_records": {"r1": {"vector": [0.1]}}, "snapshot_seq": 1, "wal_log": [{"sequence_number": 2, "op_type": "UPSERT", "record_id": "r2", "vector": [0.2]}]},
        "ALGO-VEC-UPD-139": {"active_nodes": ["node1", "node2"], "keys_to_assign": ["doc1", "doc2", "doc3"]},
        "ALGO-VEC-UPD-140": {"vector_a": {"node1": 2, "node2": 1}, "vector_b": {"node1": 2, "node2": 2}},
        "ALGO-VEC-UPD-141": {"metadata": {"source_id": "s1", "model_version": "v1", "old_title": "hello"}, "current_schema_version": 1, "target_schema_version": 2, "field_migration_map": {"old_title": "title"}},
        "ALGO-VEC-UPD-142": {"authenticated_tenant_id": "t1", "records": [{"tenant_id": "t1", "id": "1"}, {"tenant_id": "t2", "id": "2"}]},
        "ALGO-VEC-UPD-143": {"records": [{"id": "r1", "ttl_expiry_timestamp": 100.0}], "current_time": 150.0},
        "ALGO-VEC-UPD-144": {"index_vectors": [{"id": "v1", "source_id": "s1"}, {"id": "v2", "source_id": "s2"}], "authoritative_source_ids": ["s1"]},
        "ALGO-VEC-UPD-145": {"candidates": [{"id": "1", "vector": [1.0, 0.0]}, {"id": "2", "vector": [0.99, 0.01]}], "similarity_threshold": 0.95},
        "ALGO-VEC-UPD-146": {"tombstone_ratio": 0.25, "measured_recall": 0.82, "target_recall": 0.90},
        "ALGO-VEC-UPD-147": {"snapshot_records": [{"id": "r1", "vector": [0.1]}], "mutation_wal_entries": [{"sequence_number": 2, "op_type": "UPSERT", "record_id": "r2", "vector": [0.2]}]},
        "ALGO-VEC-UPD-148": {"vectors": [{"id": "1", "vector": [0.1, 0.2]}, {"id": "2", "vector": [0.3, 0.4]}], "target_segment_size": 1},
        "ALGO-VEC-UPD-149": {"full_precision_vectors": [[0.1, -0.5, 0.8]], "target_format": "INT8"},
        "ALGO-VEC-UPD-150": {"source_id": "doc123", "index_contains_id": False, "cache_contains_id": False, "shadow_index_contains_id": False},
        "ALGO-VEC-UPD-151": {"new_query_vectors": [[1.0, 0.0]], "legacy_doc_vectors": [[0.9, 0.1]], "ground_truth_relevance_pairs": [[0, 0]]},
        "ALGO-VEC-UPD-152": {"accessed_records": [{"id": "r1", "model_version": "v1.0"}], "target_model_version": "v2.0"},
        "ALGO-VEC-UPD-153": {"sample_vectors": [[0.1, 0.2, 0.3, 0.4]], "num_subvectors_m": 2, "centroids_per_subvector_k": 2},
        "ALGO-VEC-UPD-154": {"current_inverted_index": {}, "mutation_type": "UPSERT", "record_id": "r1", "metadata": {"tenant": "t1"}},
        "ALGO-VEC-UPD-155": {"vector": [0.1, 0.2], "metadata": {"tenant_id": "t1", "acl": ["read"]}},
        "ALGO-VEC-OBS-156": {"retrieved_ids": [["a", "b", "c"]], "ground_truth_ids": [["a", "b", "d"]], "k": 3},
        "ALGO-VEC-OBS-157": {"sampled_queries": [{"query_id": "q1", "embedding": [1.0, 0.0]}], "snapshot_vectors": [{"id": "d1", "embedding": [1.0, 0.0]}, {"id": "d2", "embedding": [0.0, 1.0]}], "k": 1},
        "ALGO-VEC-OBS-158": {"retrieved_ids": [["a", "b", "c"]], "relevant_ids": [["a", "c"]], "k": 3},
        "ALGO-VEC-OBS-159": {"retrieved_ids": [["x", "a", "b"]], "relevant_ids": [["a"]], "k": 10},
        "ALGO-VEC-OBS-160": {"retrieved_ids": [["a", "b"]], "ground_truth_relevance": [{"a": 2.0, "b": 1.0}], "k": 2},
        "ALGO-VEC-OBS-161": {"retrieved_ids": [["a", "b"], ["c", "d"]], "relevant_ids": [["a"], ["x"]], "k": 2},
        "ALGO-VEC-OBS-162": {"approximate_distances": [[1.05, 1.1]], "exact_distances": [[1.0, 1.0]]},
        "ALGO-VEC-OBS-163": {"judgments": [{"query_id": "q1", "context_score": 3.0, "groundedness_score": 3.0, "synthesis_score": 3.0, "failure_type": "none"}], "min_passing_score": 2.0},
        "ALGO-VEC-OBS-164": {"baseline_results": [{"query_id": "q1", "doc_ids": ["d1", "d2"]}], "candidate_results": [{"query_id": "q1", "doc_ids": ["d1", "d2"]}], "golden_expected_ids": [{"query_id": "q1", "expected_ids": ["d1", "d2"]}], "max_allowed_drop": 0.02},
        "ALGO-VEC-OBS-165": {"events": [{"session_id": "s1", "clicked_doc_id": "d1", "dwell_time_seconds": 10.0, "abandoned": False, "query_reformulated": False}], "min_dwell_threshold_seconds": 5.0},
        "ALGO-VEC-OBS-166": {"ranker_a_results": ["a1", "a2"], "ranker_b_results": ["b1", "b2"], "k": 4, "clicked_ids": ["a1"]},
        "ALGO-VEC-OBS-167": {"answer_text": "Vectors are numeric arrays.", "retrieved_passages": ["Vectors are numeric arrays in dense space."], "claims": ["Vectors are numeric arrays"]},
        "ALGO-VEC-OBS-168": {"reference_vectors": [[1.0, 0.0], [1.0, 0.1]], "current_vectors": [[1.0, 0.0], [1.0, 0.1]], "drift_threshold": 0.15},
        "ALGO-VEC-OBS-169": {"reference_sample": [[1.0, 0.0], [0.9, 0.1]], "current_sample": [[1.0, 0.0], [0.9, 0.1]], "drift_p_value_threshold": 0.05},
        "ALGO-VEC-OBS-170": {"reference_projections": [0.1, 0.2, 0.3, 0.4, 0.5], "current_projections": [0.1, 0.2, 0.3, 0.4, 0.5], "num_bins": 5},
        "ALGO-VEC-OBS-171": {"top1_scores": [0.95, 0.88, 0.82, 0.79, 0.40], "min_spread_threshold": 0.05},
        "ALGO-VEC-OBS-172": {"vectors": [[1.0, 0.0], [0.707106, 0.707106]], "expected_norm": 1.0, "tolerance": 0.05},
        "ALGO-VEC-OBS-173": {"partition_sizes": [100, 105, 98, 102], "max_allowed_imbalance_ratio": 2.0},
        "ALGO-VEC-OBS-174": {"top_k_results": [["d1", "d2"], ["d1", "d3"]], "hub_multiplier_threshold": 3.0},
        "ALGO-VEC-OBS-175": {"vectors": [[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [1.0, 1.0, 0.0]], "sample_size": 10},
        "ALGO-VEC-OBS-176": {"vectors": [{"id": "v1", "vector": [1.0, 1.0]}, {"id": "v2", "vector": [1.1, 0.9]}], "k_neighbors": 1, "outlier_z_threshold": 1.5},
        "ALGO-VEC-OBS-177": {"query_vector": [10.0, 10.0], "corpus_centroids": [[0.0, 0.0]], "max_distance_threshold": 1.2},
        "ALGO-VEC-OBS-178": {"latencies_ms": [10.0, 15.0, 20.0, 45.0, 80.0]},
        "ALGO-VEC-OBS-179": {"service_red": {"request_count": 1000, "error_count": 2, "total_duration_seconds": 20.0, "latency_p99_seconds": 0.035}, "resource_use": {"cpu_utilization_pct": 65.0, "memory_utilization_pct": 70.0, "queue_depth": 5, "disk_errors": 0}},
        "ALGO-VEC-OBS-180": {"target_slo": 0.999, "total_events": 100000, "bad_events": 50, "window_hours": 24.0},
        "ALGO-VEC-OBS-181": {"traceparent": "00-4bf92f3577b34da6a3ce929d0e0e4736-00f067aa0ba902b7-01", "spans": [{"span_id": "s1", "name": "vector_search", "duration_ms": 25.0, "status": "OK"}]},
        "ALGO-VEC-OBS-182": {"mutation_events": [{"source_timestamp": 100.0, "index_timestamp": 102.0, "status": "COMMITTED"}], "max_allowed_lag_seconds": 60.0},
        "ALGO-VEC-OBS-183": {"adjacency_list": {"0": ["1", "2"], "1": ["0"], "2": ["0"]}, "entry_points": ["0"]},
        "ALGO-VEC-OBS-184": {"segments": [{"segment_id": "seg1", "active_records_count": 1000, "tombstone_records_count": 250, "size_bytes": 1000000}], "compaction_threshold_ratio": 0.20},
        "ALGO-VEC-OBS-185": {"cache_metrics": {"hits": 850, "misses": 150, "evictions": 10}, "memory_stats": {"used_bytes": 1073741824, "total_allocated_bytes": 2147483648, "fragmentation_pct": 5.0}, "min_acceptable_hit_ratio": 0.8},
        "ALGO-VEC-OBS-186": {"arrival_rate_qps": 200.0, "mean_latency_seconds": 0.05, "p99_latency_seconds": 0.15, "headroom_ratio": 0.4, "max_threads_per_replica": 32},
        "ALGO-VEC-OBS-187": {"partitions": [{"partition_id": 0, "log_end_offset": 5000, "current_consumer_offset": 4800}], "consumption_rate_per_sec": 500.0, "max_acceptable_lag_records": 5000},
        "ALGO-VEC-OBS-188": {"labels": {"tenant_id": "tenant-1", "status": "200", "user_uuid": "123e4567-e89b-12d3-a456-426614174000"}, "allowed_label_keys": ["tenant_id", "status"]},
        "ALGO-VEC-OBS-189": {"metric_series": [10.0, 11.0, 10.5, 10.2, 50.0], "alpha": 0.2, "sigma_threshold": 2.0},
        "ALGO-VEC-OBS-190": {"shard_data_streams": [[10.0, 20.0, 30.0], [40.0, 50.0]], "quantiles_to_query": [0.5, 0.9]},
        "ALGO-VEC-OBS-191": {"query_id": "q-1", "stages": [{"stage_name": "pre_filter", "candidates_in": 1000, "candidates_out": 200, "duration_ms": 1.5}, {"stage_name": "hnsw_search", "candidates_in": 200, "candidates_out": 10, "duration_ms": 5.0}]},
        "ALGO-VEC-OBS-192": {"trace_payload": {"query_id": "q-99", "query_text": "confidential user query", "duration_ms": 25.0, "has_error": False}, "sample_rate": 1.0},
        "ALGO-VEC-OBS-193": {"vectors": [[1.0, 0.5, 0.2], [0.2, 0.8, 0.1], [0.5, 0.2, 0.9]], "target_dimensions": 2},
        "ALGO-VEC-OBS-194": {"failed_queries": [{"query_id": "q1", "text": "error 500", "embedding": [0.9, 0.1]}, {"query_id": "q2", "text": "http 500 crash", "embedding": [0.88, 0.12]}], "cluster_distance_threshold": 0.5},
        "ALGO-VEC-OBS-195": {"canary_query_results": [{"probe_id": "p1", "success": True, "latency_ms": 12.0}], "isolation_probe_results": [{"probe_id": "iso1", "leak_detected": False}]},
        "ALGO-VEC-OBS-196": {"comparisons": [{"query_id": "q1", "prod_doc_ids": ["d1", "d2"], "shadow_doc_ids": ["d1", "d2"], "prod_latency_ms": 15.0, "shadow_latency_ms": 12.0}], "min_jaccard_threshold": 0.6},
        "ALGO-VEC-OBS-197": {"vector_records": [{"vector_id": "vec-100", "source_doc_id": "doc.pdf", "chunk_id": "c1", "model_version": "v1.0", "created_at": 100.0}]},
        "ALGO-VEC-OBS-198": {"source_database_ids": ["doc-1", "doc-2"], "vector_index_ids": ["doc-1"]},
        "ALGO-VEC-OBS-199": {"queries_count": 10000, "total_tokens_embedded": 500000, "total_reranked_passages": 50000, "indexed_vector_count": 1000000, "vector_dimension": 768, "precision_bytes": 4},
        "ALGO-VEC-OBS-200": {"failure_clusters": [{"size": 3, "sample_queries": ["query-alpha"]}], "ood_queries": ["query-beta"], "current_recall": 0.75, "target_recall": 0.90},
        "ALGO-CLS-01": {"file_path": "pyproject.toml", "probe_bytes": 8192},
        "ALGO-CLS-02": {"file_path": "pyproject.toml", "max_lines_to_check": 20},
        "ALGO-CLS-03": {"file_path": "pyproject.toml"},
        "ALGO-CLS-04": {"file_path": "pyproject.toml", "max_bytes": 1000000, "max_lines": 50000},
        "ALGO-TRFM-01": {"text": "banana", "sentinel": "$"},
        "ALGO-TRFM-02": {"integers": [10, 20, 30]},
        "ALGO-TRFM-03": {"integers": [10, 20, 30]},
        "ALGO-TRFM-04": {"values": [1, 2, 3, 100], "block_size": 64},
        "ALGO-TRFM-05": {"integers": [1, 5, 10, 25]},
        "ALGO-TRFM-06": {"text": "banana"},
        "ALGO-TRFM-07": {"file_path": "example.py", "code": "def foo(): pass"},
        "ALGO-TRFM-08": {"query_tree": {"op": "AND", "children": ["a", "b"]}},
        "ALGO-TRFM-09": {"text": "hello Exception occurred", "pattern": r"\w+Exception"},
        "ALGO-TRFM-10": {"pattern": r"function_name\d+"},
        "ALGO-TRFM-11": {"pattern": r"abc(def|ghi)"},
    }

    assert len(BUILTIN_ALGORITHM_CONTRACTS) >= 242


    from src.api.cli.main import build_parser, handle_algo_command
    import io
    from contextlib import redirect_stdout

    parser = build_parser()

    for contract in BUILTIN_ALGORITHM_CONTRACTS:
        algo_id = contract.id
        if algo_id not in test_inputs:
            continue
        inp_json = json.dumps(test_inputs[algo_id])
        args = parser.parse_args(["algo", "execute", "--id", algo_id, "--input", inp_json, "--json"])
        
        f = io.StringIO()
        with redirect_stdout(f):
            exit_code = handle_algo_command(args)
        assert exit_code == 0, f"CLI execution failed for {algo_id}"
        parsed = json.loads(f.getvalue())
        assert "algo_id" in parsed
        assert parsed["algo_id"] == algo_id
        assert "result" in parsed
